### ISSUE TITLE
Test fails for an input change that modifies the state using a dynamic key

### ISSUE THREAD

**Issue by MichelleFernandez** [enzymejs/enzyme#2138]
Thanks for reporting an issue to us! We're glad you are using and invested in Enzyme.
Before submitting, please read over our commonly reported issues to prevent duplicates!

### All common issues

* [common issues](../blob/master/docs/common-issues.md)

### Notoriously common issues

* [Webpack build issues](../blob/master/docs/common-issues.md#webpack-build-issues)
* [Cannot find module 'react-dom/lib/ReactTestUtils'](../blob/master/docs/common-issues.md#error-cannot-find-module-react-domlibreacttestutils)
* [Query Selector fails](../blob/master/docs/common-issues.md#query-selector-fails)
* [Testing third party libraries](../blob/master/docs/common-issues.md#testing-third-party-libraries)

If you haven't found any duplicated issues, please report it with your environment!

### Current behavior
My test **fails** for an input change that modifies the `state` using a dynamic key:
```
  ● Login component › tests email input onChange

    expect(received).toEqual(expected)

    Expected value to equal:
      "test@me.com"
    Received:
      ""

      69 |       .simulate("change", { target: { value: "test@me.com" } });
      70 |
    > 71 |     expect(component.state("email")).toEqual("test@me.com");
         |                                      ^
      72 |   });
      73 |
      74 |   it("tests password input onChange", () => {

      at Object.toEqual (src/components/auth/Login.spec.js:71:38)
```
Here is my implementation:
``` 
<Input id="email" value={this.state.email} onChange={this.updateInputValue} />

updateInputValue(evt) {
  this.setState({
    [evt.target.id]: evt.target.value
  });
}

it("tests email input onChange", () => {
  const component = shallow(<Login />);

  component
    .find('#email')
    .simulate("change", { target: { value: "test@me.com" } });

  expect(component.state("email")).toEqual("test@me.com");
});
```
I noticed this issue when I tried setting the `state` with a static key, and **the test passed:** 
```
updateInputValue(evt) {
  this.setState({
    email: evt.target.value
  });
}
```
I tried to validate that the dynamic keys were indeed the problem by setting the `state` doing so directly inside the test code, but **the test passed**:
```
  it("tests email input onChange", () => {
    const component = shallow(<Login />);

    // component
    //   .find("#email")
    //   .simulate("change", { target: { value: "test@me.com" } });

    let key = "email";
    component.setState({ [key]: "test@me.com" });
    expect(component.state("email")).toEqual("test@me.com");
  });
```
Finally, tried this workaround, surprisingly with no luck, **the test failed** (notice I am using static keys inside each `if` clause):
```
updateInputValue(evt) {
    let key = evt.target.id;
    if (key === "email") {
      console.log('email')
      this.setState({
        email: evt.target.value
      });
    } else if (key === "password") {
      console.log('password')
      this.setState({
        password: evt.target.value
      });
    }
}
```

### Expected behavior
That the test passes even when setting a `state` property with a dynamic key.

### Your environment
`create-react-app`

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.9.0
| react               | 16.8.6
| react-dom           | 16.8.6
| react-test-renderer | 16.8.6
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by depombo** [comment]
+1

**Comment by ljharb** [comment]
Try adding a `wrapper.update()` - but really, don't use `.simulate` at all, since it doesn't faithfully simulate anything.

If you're trying to invoke the `onChange` prop, then do `.prop('onChange')()` - firing "simulate" doesn't actually do anything but that.

**Comment by depombo** [comment]
>  but really, don't use `.simulate` at all, since it doesn't faithfully simulate anything.

This is confusing considering that `simulate` is used all over the examples in the README and here https://airbnb.io/enzyme/#basic-usage 

Also the example @MichelleFernandez points is not a prop change. But testing an event handler firing and changing the state accordingly. What is the best way to do this or is there an up to date guide?

**Comment by ljharb** [comment]
@depombo thanks, i'll expunge it from the examples.

If you want to call the onChange prop, you should do `.prop('onChange')()`.

However, the real issue is that you're setting the state key based on `event.target.id`, but your mock in tests lacks an `id` property.

**Comment by IamAbhii** [comment]
I am not sure you got the solution or not but I would suggest try this following code.
`<Input id="email" value={this.state.email} onChange={this.updateInputValue} />

updateInputValue(evt) {
  this.setState({
    [evt.target.id]: evt.target.value
  });
}

it("tests email input onChange", () => {
  const component = shallow(<Login />);

  component
    .find('#email')
    .simulate("change", { target: { id:"email",value: "test@me.com" } });

  expect(component.state("email")).toEqual("test@me.com");
});`

**Comment by ljharb** [comment]
This seems answered.
