### ISSUE TITLE
Invariant Violation: got Symbol, while using mount()

### ISSUE THREAD

**Issue by stilian9205** [enzymejs/enzyme#2208]
I am trying to test my component which is nothing fancy. But when I import it in the test file and try to load it I get the following error

> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: symbol.

**EDIT:** When I copy the code of the component into the test file instead of importing it, everything works fine, I thought it was worth mentioning.

Here is my code:

```jsx
import React from 'react';
import { mount } from 'enzyme';
import sinon from 'sinon';
import AuditInvestigator from './AuditInvestigator';
import axios from 'axios';

describe('Test Audit Investigator ', () => {
  let wrapper;


  beforeEach(() => {
    wrapper = mount(<AuditInvestigator />)
  })

  it('should contain state', () => {
    expect(wrapper.state()).toEqual({
      cancelToken: axios.CancelToken.source()
    })
  })

})
```

If you have any ideas I am open, or you need more info of my code I will provide it.

Audit Investigator content: 

```jsx
import React from 'react';
import PropTypes from 'prop-types';
import autoBind from 'react-autobind';
import { AuditInvestigatorLayout } from './AuditInvestigatorLayout';
import { reworkRawAllActivityLogsData, reworkUsersData } from '../.././utils/rework-activity-log-data';
import axios from 'axios';

class AuditInvestigator extends React.Component {
  constructor(props) {
      super(props);
      autoBind(this);
      this.state = {
        cancelToken: axios.CancelToken.source()
      }
  }

  componentWillMount = () => {
    this.props.requestAllUsers();
    if(this.props.selectedUser.value !== '0') {
      this.props.requestAllLogs({cancelToken: this.state.cancelToken, userId: this.props.selectedUser.value});
    }
  }

  onGridReady(params) {
    this.gridApi = params.columnApi;
  }

  componentDidUpdate = () => {
    if (this.gridApi) {
      var allColumnIds = [];
      this.gridApi.getAllColumns().forEach(function(column) {
        allColumnIds.push(column.colId);
      });
      this.gridApi.autoSizeColumns(allColumnIds);
    }
  };

  componentWillUnmount = () => {
    this.state.cancelToken.cancel('operation canceled')
    this.props.requestAllLogsSuccess({logsData: []})
  }

  onUsersSelectChange = (e) => {
    this.props.changeLogsUser(e);
    this.props.requestAllLogs({cancelToken: this.state.cancelToken, userId: e.value});
  }

  render() {
    return (
      <div>
        <AuditInvestigatorLayout
          hideLogsLoader={this.props.hideLogsLoader}
          logsData={reworkRawAllActivityLogsData(this.props.logsData)}
          onGridReady={this.onGridReady}
          usersData={reworkUsersData(this.props.usersData)}
          onUsersSelectChange={this.onUsersSelectChange}
          usersHideLoader={this.props.usersHideLoader}
          selectedUser={this.props.selectedUser}
        />
      </div>
    );
  }
}

AuditInvestigator.propTypes = {
  hideLogsLoader: PropTypes.bool,
  logsData: PropTypes.array,
  requestAllLogs: PropTypes.func,
  history: PropTypes.object,
  requestAllLogsSuccess: PropTypes.func,
  requestAllUsers: PropTypes.func,
  selectedUser: PropTypes.object,
  changeLogsUser: PropTypes.func,
  usersData: PropTypes.array,
  usersHideLoader: PropTypes.bool
};

export default AuditInvestigator;
```
- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |   3.9.0
| react               |      16.3.1
| react-dom           |  16.2.0
| react-test-renderer |  16.0.0
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
(as a side note; you shouldn't have functions in class fields, but especially not lifecycle methods, which never ever need to be bound to the instance; also, using `autoBind` is very slow)

If, when you inline the code, it all works, that suggests something about the importing isn't working. What test runner are you using? In your test with the import, if you `console.log(AuditInvestigator)`, what do you get?

**Comment by cyberSane** [comment]
I am facing the similar issue but it started happing after updating the react version from 16.1 to 16.4.

Below are the other dependency version we I am using:
"enzyme": "^3.7.0"
"jest": "^23.6.0"
"enzyme-adapter-react-16": "^1.6.0"

**Comment by ljharb** [comment]
@cyberSane please file a new issue with your code; I'm going to close this one since the OP never responded.

**Comment by cyberSane** [comment]
fyi, I got the answer. The reason of the above error is due to incompatible version of react and react-dom. In the above query of @stilian9205, 
react version is 16.3.1 and react-dom version is 16.2.0.
Changing the react-dom version to ~16.3 will work.

**Comment by ljharb** [comment]
Indeed, those two must always be on the same minor version.
