### ISSUE TITLE
Using mount on <video> with muted=true causes React console.error

### ISSUE THREAD

**Issue by fbontin** [enzymejs/enzyme#2326]
### Current behavior
When using `mount` on a component with a video tag which is muted,  React throws an error. If the muted attribute is removed, then no error is logged.

Code example: 
```
describe('Mounting this component causes React DOM to log an error', () => {
  const Component = () => (
    <video muted>
      <source src="url" />
    </video>
  );

  it('Will it?', () => {
    const wrapper = mount(<Component />);
  });
});
```

Even if the component is only `<video muted />` it still happens.

Output in test:
```
console.error node_modules/react-dom/cjs/react-dom.development.js:530
    Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering.
        in video (created by Comp)
        in Comp (created by WrapperComponent)
        in WrapperComponent
```

### Expected behavior
There should be no printed error.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10.0
| react               | 16.12.0
| react-dom           | 16.12.0
| react-test-renderer | 16.10.1
| adapter (below)     | 1.14.0

#### Adapter

- [x] enzyme-adapter-react-16

PS. First time opening an issue here, I hope I didn't miss anything

**Comment by ljharb** [comment]
Interesting; presumably React itself works fine. Can you try with enzyme v3.11.0, and with v1.15.2 of the adapter, and confirm the problem still exists?

Also, are you *sure* you don't have any version of `react-test-renderer` in your tree, whether it's a direct dep or not?

**Comment by fbontin** [comment]
Hi, thanks for the quick answer! I do have `react-test-renderer` (version 16.10.1) as a dependency from `enzyme-adapter-react-16`, I will update my first comment. 

I tried your suggestion and it still happens, these are the versions:

library | version
-- | --
enzyme | 3.11.0
react | 16.12.0
react-dom | 16.12.0
react-test-renderer | 16.10.1
enzyme-adapter-react-16 | 1.15.2

**Comment by ljharb** [comment]
Thanks; that update was going to be my next question.

Can you make a PR with a failing test case? I'd be happy to fix it with a repro.

**Comment by fbontin** [comment]
Yeah sure! Could you point me in the right direction? Like where I should put the test?

**Comment by ljharb** [comment]
Ideally one in both shallow and mount - so one in https://github.com/airbnb/enzyme/blob/master/packages/enzyme-test-suite/test/ShallowWrapper-spec.jsx, and one in https://github.com/airbnb/enzyme/blob/master/packages/enzyme-test-suite/test/ReactWrapper-spec.jsx :-) Thanks!

**Comment by fbontin** [comment]
Thanks for the help! The PR is created, I hope it's what you expected :-)

**Comment by davidhouweling** [comment]
@ljharb any update on this issue?

**Comment by ljharb** [comment]
This appears to be the same issue as https://github.com/testing-library/react-testing-library/issues/470 as well as https://github.com/facebook/react/issues/10389 - this isn't something that's possible to fix in enzyme.

I'll leave #2330 open, however - if react ever fixes it, i'll land the test case to ensure it doesn't regress in the future.
