### ISSUE TITLE
wrapper instance returns null

### ISSUE THREAD

**Issue by rahulxyz** [enzymejs/enzyme#2331]
We are using antd, react and testing using jest and enzyme.
```
it("should render without error", () => {
    let component = (
      <Provider store={store}>
        <FillUpRFQDetails form={testForm} />
      </Provider>
    );
    let wrapper = mount(component);
    console.log(wrapper.instance()) 
     
    expect(wrapper).toBeDefined();
})
```
We normally are able to trigger methods in react using instance() but in this case it returns null.

**Comment by duanbaosheng** [comment]
i   have the same question with you.

**Comment by duanbaosheng** [comment]
how to  solve the problem?

**Comment by ljharb** [comment]
In react 16, functional components as well as forwardRef/memo components do not have an instance. Presumably your Provider is one of these.

I’d suggest using the wrappingComponent option for the Provider instead of putting it inline.
