### ISSUE TITLE
On mocking function toHaveBeenCalledTimes() returns 0 

### ISSUE THREAD

**Issue by rahulxyz** [enzymejs/enzyme#2334]
**My Component**
```jsx
import React from "react";
import { withRouter } from "react-router-dom";
import { Icon } from "antd";

const handleGoBack = (history, returnPath) => {
  if (returnPath) {
    history.push(returnPath);
  } else {
    history.goBack();
  }
};

const GoBack = ({ history, returnPath }) => (
  <span onClick={() => handleGoBack(history, returnPath)} style={{ cursor: "pointer" }}>
    <Icon type="arrow-left" />
  </span>
);

export default withRouter(GoBack);
```

**Test**
```jsx
import React from "react";
import { shallow, mount } from "enzyme";
import GoBack from "./GoBack";
import { BrowserRouter as Router } from "react-router-dom";

const returnPath = "/manage-rfq";

describe("GoBack", () => {
  let wrapper;
  const history = {
    goBack: jest.fn(),
    push: jest.fn()
  };

  it("should not push in history", () => {
    wrapper = mount(
      <Router>
        <GoBack />
      </Router>
    );
    wrapper.simulate("click");
  // this returns 0 although that method is getting called`
    expect(history.goBack).toHaveBeenCalledTimes(1);
  });

});
```

**Error:**
```
● GoBack › should not push in history

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      29 |     wrapper.simulate("click");
    > 31 |     expect(history.goBack).toHaveBeenCalledTimes(1);
         |                            ^
      32 |   });
```

**Comment by ljharb** [comment]
I'd suggest avoiding `simulate`; it does not actually simulate anything. (also, if you stick `jsx` after your triple backticks, it syntax highlights and makes code snippets readable)

Can you try `.invoke('onClick')()` instead?

**Comment by venu-3** [comment]
.invoke('onClick) is not working for me. Can anyone please help out of this

**Comment by ljharb** [comment]
@venu-3 your example is using simulate, not invoke.

Separately, `const history` defines it for the `describe`, and *nothing outside of that* can access it.

In other words, the OP's example makes no sense, since the `history` mock is entirely unused.

Closing pending a repro.

**Comment by RehanRabbani** [comment]
import React from "react";
import { shallow, mount } from "enzyme";
import GoBack from "./GoBack";
import { BrowserRouter as Router } from "react-router-dom";

const returnPath = "/manage-rfq";

describe("GoBack", () => {
  let wrapper;
  const handleGoBack = jest.fn();
  it("should not push in history", () => {
    wrapper = shallow(
      <Router>
        <GoBack />
      </Router>
    );
    wrapper.simulate("click");
    expect(handleGoBack).toHaveBeenCalledTimes(1);
  });

});

**Comment by ljharb** [comment]
@RehanRabbani use `wrappingComponent` for `Router`, and avoid `simulate` since it doesn't simulate anything - if you want to invoke `onClick`, use `.invoke('onClick')()`.
