### ISSUE TITLE
404 for https://airbnb.io/enzyme/

### ISSUE THREAD

**Issue by psabharwal123** [enzymejs/enzyme#2342]
Thanks for reporting an issue to us! We're glad you are using and invested in Enzyme.
Before submitting, please read over our commonly reported issues to prevent duplicates!

### All common issues

* [common issues](../blob/master/docs/common-issues.md)

### Notoriously common issues

* [Webpack build issues](../blob/master/docs/common-issues.md#webpack-build-issues)
* [Cannot find module 'react-dom/lib/ReactTestUtils'](../blob/master/docs/common-issues.md#error-cannot-find-module-react-domlibreacttestutils)
* [Query Selector fails](../blob/master/docs/common-issues.md#query-selector-fails)
* [Testing third party libraries](../blob/master/docs/common-issues.md#testing-third-party-libraries)

If you haven't found any duplicated issues, please report it with your environment!

### Current behavior
https://airbnb.io/enzyme/ gives 404

### Expected behavior
it should not give a 404

#### API

- [ ] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 
| react               | 
| react-dom           | 
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [ ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
The docs now live at https://github.com/enzymejs.

**Comment by psabharwal123** [comment]
@ljharb can we add a redirect for everyone who has it bookmarked?

**Comment by ljharb** [comment]
It's being looked into.

**Comment by lencioni** [comment]
@psabharwal123 I had hit a few snags getting the redirects set up correctly yesterday, but I think I've ironed most of them out now. Can you let me know if you find any URLs that aren't redirecting properly for you?
