### ISSUE TITLE
Breaking change in 3.11.0?

### ISSUE THREAD

**Issue by SantoJambit** [enzymejs/enzyme#2362]
No duplicate issues found.

### Current behavior

Some of my tests don't work anymore after upgrade from 3.10.0 to 3.11.0.
I'm using a setup like this:
```javascript
const wrapper = mount(component, rendererOptions);
expect(wrapper.find('h3').children().length).toEqual(1); // received 3
```

### Expected behavior

It should still only return 1 child here.

### Your environment

- Ubuntu 18.04
- Node 13.12.0

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.11.0
| react               | 16.13.1
| react-dom           | 16.13.1
| react-test-renderer | -
| adapter (below)     | 1.15.2

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
What's `wrapper.find('h3').children().debug()`?

**Comment by SantoJambit** [comment]
Sorry about the delay.. this is the result:

```
dummy title
    
    
     
    
    
    <SearchTag>
      <span>
        ADMIN
      </span>
    </SearchTag>
```

It's a bit weird with all the whitespace & stuff. Not sure if this may be related to the component is being rendered into a portal. Still, it works with the last version, so something must have changed.

**Comment by ljharb** [comment]
hmm, could you share the implementation of the component, as well as `wrapper.debug()`'s output?

**Comment by SantoJambit** [comment]
Okay, so I've broken this down to a simple scenario:

```
            const wrapper = mount(
            <h3>
                {'title'}
                {' '}
                <div>more</div>
            </h3>);
            expect(wrapper.find('h3').children().length).toEqual(1);
```

Looking at this, I can see, that text nodes might now be defined as children, but that hasn't been the case before. Is this change intended?

**Comment by ljharb** [comment]
Yes, that's a bug fix - they were always supposed to have been separate children. That's 3 children; if you want to filter out the text nodes, you can use `.filter` to do that.

**Comment by SantoJambit** [comment]
ok, thanks, will close this then.
