### ISSUE TITLE
Shallow rendering with wrappingcomponent option sets empty context object

### ISSUE THREAD

**Issue by marnixhoh** [enzymejs/enzyme#2374]
### Current behavior
When shallow rendering a component that depends on some context using the 'wrappingcomponent' option results in an empty object being set on the context:

```
test('Should correctly render component', () => {
    const wrapper = shallow(<MyComponent/>, {
        wrappingComponent: (props) => <Provider someContext={{test: 'test'}}>{props.children}</Provider> })
    expect(wrapper).toMatchSnapshot()
})
```
This results in the followings props being received by MyComponent:
`props = { someContext = {} }`
I.e. the someContext property is an empty object..
### Expected behavior
The expected behavior is to have the props received by MyComponent to be:
`props = { someContext = { test: 'test' } }`

This does appear to be the case when using mount instead of shallow, but for some of my elements this is not an option.

### Your environment
Node + Jest

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.11.0
| react               | 16.13.1
| react-dom           | 16.13.1
| react-test-renderer | /
| adapter (below)     | 1.15.2

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by webel** [comment]
Having the same issue, quite annoying as I have to mock out the behaviour differently for shallow rendering and mounts which I both use. And because it's shallow, just wrapping the component before passing to shallow means only the provider is rendered.

**Comment by ljharb** [comment]
@marnixhoh your issue is that you're passing `WrappingComponent` as an arrow function, instead of just passing `Provider`, and using `wrappingComponentProps` to pass the context prop.

@webel please file a new issue if that's not a solution for you.
