### ISSUE TITLE
Simulate click not working. Why?

### ISSUE THREAD

**Issue by Georg127** [enzymejs/enzyme#2376]
### Current behavior

Simulate click is not working. I guided by documentation. It doesn't work. Maybe i'm doing something wrong?

```jsx
describe('<NewsListContainer /> componentDidMount', () => {
    it('onClick', () => {
        const nextProps = {
            ...props,
            isLoaded: true,
        }
        const onButtonClick = sinon.spy();
        const wrapper = shallow(
        <Provider store={store}>
            <NewsContainers handleClick={onButtonClick} {...nextProps} />
                </Provider>
);      wrapper.simulate('click');
        expect(onButtonClick).toHaveProperty('callCount', 1);
    });
  })

```
```jsx
Component 
class Component extends React.Component<Props> {
  componentDidMount() {
    const { args } = this.props;
    requestDefault(args);
  }
  
  render() {
    const { args } = this.props;
    const react = args.map((list: any) => {
      return (
        <Content
          {list.content}
        />
    )});
    return (
      <div className="bar">
      {react}
<div className="sort-button">
        //Material Ui  
                <Fab
                  variant="extended"
                  color="primary"
                  aria-label="add"
                  onClick={this.handleClick}
                >
                  <KeyboardArrowUpIcon
                 />
                  Sort
                </Fab>
      </div>
    );
  }
}

const mapStateToProps = (state: AppStateType) => ({
  arg: state.list.arg,
  arg: state.list.arg,
  arg: state.list.arg,
  arg: state.list.arg,
  arg: state.list.arg,
  requestDefault: requestDefault(state),
});

export default connect(mapStateToProps, {
  requestDefault: requestDefault,
})(Component);
````

### Expected behavior

Click should work

### Your environment

Create-react-app + redux+ jest + enzyme + typescript

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  ^3.11.0
| react               |  16.13.1
| react-dom           |  16.13.1
| react-test-renderer |  / 
| adapter (below)     |  1.18.1

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
I'd suggest not using simulate; it doesn't faithfully simulate anything.

Also, use the `wrappingComponent` option for your Provider rather than passing it directly in.

If you want to invoke the `onClick` prop, use `.invoke` to do so directly.

**Comment by Georg127** [comment]
> I'd suggest not using simulate; it doesn't faithfully simulate anything.
> 
> Also, use the `wrappingComponent` option for your Provider rather than passing it directly in.
> 
> If you want to invoke the `onClick` prop, use `.invoke` to do so directly.

Ok, i'm testing another function without redux connect. It has method handleClick(). in <a> tag( <Link />)
```
  const onButtonClick = sinon.spy();
  const wrapper = shallow(<NewsList {...props}/>);
  wrapper.find('.click-link').simulate('onClick');
  expect(onButtonClick).toHaveProperty('callCount', 1)
```

return 

```
expect(received).toHaveProperty(path, value)

    Expected path: "callCount"

    Expected value: 1
    Received value: 0

      46 |   const wrapper = shallow(<NewsList {...props}/>);
      47 |   wrapper.find('.click-link').invoke('onClick');
    > 48 |   expect(onButtonClick).toHaveProperty('callCount', 1)
         |                         ^
      49 |   });
      50 | });
```
