### ISSUE TITLE
isEmptyRender does not work as expected on memo'd FCs

### ISSUE THREAD

**Issue by wezleytsai** [enzymejs/enzyme#2377]
### Current behavior
`wrapper.isEmptyRender()` returns `true` for a component that returns `null`. However, if the component is memoized, `wrapper.isEmptyRender()` returns `false`.

### Expected behavior
Memoized or not, `wrapper.isEmptyRender()` to return `true` when component returns `null`.

### Your environment
See reproducible: https://codesandbox.io/s/goofy-worker-zzing

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.11.0
| react               | 16.13.1
| react-dom           | 16.13.1
| react-test-renderer | 
| adapter (below)     | 1.15.2

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by 9oelM** [comment]
I believe I am experiencing a similar issue. 
Almost exactly same as your codesandbox code:

```ts
const Component = React.memo(() => null)
const wrapper = mount(<Component />)
expect(wrapper.isEmptyRender()).toBe(true)
```

It will return true. As a workaround, I used `expect(wrapper.html()).toBe(``)`
