### ISSUE TITLE
React Native components transform into generic one with shallow

### ISSUE THREAD

**Issue by brian-perlego** [enzymejs/enzyme#2379]
### Current behavior

After updating to React Native 62 some of my unit test are not working. The component is not rendered correctly using shallow(). For exemple if I try to shallow a component that include a TextInput and then I console log debug it I will receive this:

```
<Component autoCorrect={false} autoCapitalize="none" onFocus={[Function]} ... />
```
instead of what I got before

```
<TextInput autoCorrect={false} autoCapitalize="none" onFocus={[Function]} ... />
```

It's happening with other components (TouchableOpacity and TouchableHighlight)

### Expected behavior

The React Native component to be the same instead of a generic one.

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10.0
| react               | 16.11.0
| react-native     | 0.62.2
| react-dom           | 16.11.0
| react-test-renderer | 16.11.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
See #1436 - without an official RN adapter, RN doesn't work properly with enzyme. `enzyme-adapter-react-16` is for ReactDOM.

**Comment by gerryfletch** [comment]
I had the same issue with TouchableOpacity and TextInput. Found this discussion which lead to a workaround for me: https://github.com/facebook/react-native/issues/27721

**Comment by brian-perlego** [comment]
Thank you @gerryfletch, [this fixed my issue](https://github.com/facebook/react-native/issues/27721#issuecomment-609052183)
