### ISSUE TITLE
Function inside one test appears to be called in the other tests

### ISSUE THREAD

**Issue by iurietarlev** [enzymejs/enzyme#2380]
I am testing a component with one submit button. The onClick for this submitButton calls a function that is passed into the component.

### Test Code
```jsx
  describe("AddItem ", () => {
  let wrapper;
  const addItemMock = jest.fn();

  beforeEach(() => {
    wrapper = mount(
      <AddItemModal
        addItem={addItemMock}
      />
    );
  });

  it("when submit is clicked, addItemMock is called", () => {
    wrapper.find("#submitButton").simulate("click");
    expect(addItemMock).toHaveBeenCalled();
  });

  it("something else to be tested", () => {
    expect(addItemMock).not.toHaveBeenCalled();
  });
});
```
### Current behavior
The first test passes with no problems. In the context of the second test, the received number of calls for addItemMock is 1, but expected is zero. 

### Expected behavior
The addItemMock function should not appear to have been called during the second test. 

I was wondering how are the two contexts of the two tests are linked to each other and how can it be broken, as if I change the order of the tests inside the "describe", the test passes with no problems.

#### API

- [ ] shallow
- [x ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.11.0
| react               |  16.13.1
| react-dom           | 16.13.1
| react-test-renderer |  16.13.1
| adapter (below)     |  1.15.2

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
This is because you're defining `addItemMock` inside the `describe` instead of the `beforeEach` - which means you're using the same one in both tests, and the first test calls it.

Either reset it in an `afterEach`, or define it in `beforeEach`.
