### ISSUE TITLE
Cannot find module 'entities/lib/maps/entities.json'

### ISSUE THREAD

**Issue by Innei** [enzymejs/enzyme#2404]
# Current behavior

```
FAIL  __tests__/header.spec.tsx
  ● Test suite failed to run

    Cannot find module 'entities/lib/maps/entities.json' from 'node_modules/htmlparser2/lib/Tokenizer.js'

    Require stack:
      node_modules/htmlparser2/lib/Tokenizer.js
      node_modules/htmlparser2/lib/Parser.js
      node_modules/htmlparser2/lib/index.js
      node_modules/cheerio/lib/parse.js
      node_modules/cheerio/lib/cheerio.js
      node_modules/cheerio/index.js
      node_modules/enzyme/build/Utils.js
      node_modules/enzyme/build/ReactWrapper.js
      node_modules/enzyme/build/index.js
      enzyme.js
```
and my jest.config.js

```js
/*
 * @Author: Innei
 * @Date: 2020-06-13 11:08:49
 * @LastEditTime: 2020-06-13 12:15:45
 * @LastEditors: Innei
 * @FilePath: /mx-web/jest.config.js
 * @Coding with Love
 */
const path = require('path')
module.exports = {
  roots: ['<rootDir>/'],
  rootDir: './',
  moduleFileExtensions: ['ts', 'tsx', 'js'],
  collectCoverageFrom: [
    '**/*.{js,jsx,ts,tsx}',
    '!**/*.d.ts',
    '!**/node_modules/**',
  ],
  testPathIgnorePatterns: ['/node_modules/', '/.next/'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
    '^.+\\.(js|jsx)$': '<rootDir>/node_modules/babel-jest',
    '^.+\\.css$': '<rootDir>/configs/jest/cssTransform.js',
  },
  testMatch: ['**/*.(test|spec).(ts|tsx)'],
  coveragePathIgnorePatterns: ['/node_modules/', 'enzyme.js'],
  setupFilesAfterEnv: ['<rootDir>/enzyme.js'],
  coverageReporters: ['json', 'lcov', 'text', 'text-summary'],
  globals: {
    'ts-jest': {
      useBabelrc: true,
      tsConfigFile: 'jest.tsconfig.json',
    },
  },
  transformIgnorePatterns: [
    '/node_modules/',
    '^.+\\.module\\.(css|sass|scss)$',
  ],
  moduleNameMapper: {
    '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/mocks.js',
    '\\.(css|less|scss)$': '<rootDir>/__mocks__/mocks.js',
  },
  moduleDirectories: [path.resolve(__dirname, 'node_modules'), '<rootDir>/'],
}

```

please help me, thank you!

### Expected behavior

test pass

### Your environment

macOS 10.15.2
node 12@latest

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | ^3.11.0
| react               | 16.3.1
| react-dom           | 16.13.1
| react-test-renderer | 16.13.1
| adapter (below)     | 16

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
You forgot to include `.json` in your `moduleFileExtensions`.

**Comment by SabrinaFZ** [comment]
> You forgot to include `.json` in your `moduleFileExtensions`.

I have the same problem and I have included the .json

**Comment by ljharb** [comment]
@SabrinaFZ can you provide the same info that the OP provided, either here or in a new issue?

**Comment by goldEli** [comment]
> You forgot to include `.json` in your `moduleFileExtensions`.

I have the same problem and I have included the .json

**my jest.config.js:**
![image](https://user-images.githubusercontent.com/18217162/96210010-92170480-0fa3-11eb-98fb-c8fd78d2d9ef.png)

**my file directory structure:**
```
- src
- config
  - jest.config.js
  - cssTransfom.js
  - enzymeConfig.js
  - fileTransform.js 
```
**current behavior:**
![image](https://user-images.githubusercontent.com/18217162/96210287-2719fd80-0fa4-11eb-885d-8b35950af904.png)

**Comment by ljharb** [comment]
Why is the folder in node modules called “_htmlparser2@3.10.1@htmlparser2”? That’s not a valid package name, and version numbers aren’t part of the file structure.

**Comment by goldEli** [comment]
> Why is the folder in node modules called “_htmlparser2@3.10.1@htmlparser2”? That’s not a valid package name, and version numbers aren’t part of the file structure.

thank you so much @ljharb 
I used [cnpm](https://github.com/cnpm/cnpmjs.org) to install my packages before,  and the problem was fixed after swtiching to npm
maybe cnpm bug

**Comment by ljharb** [comment]
Definitely. Anything that works with npm but doesn't work with an alternative package manager is a bug in that package manager.

**Comment by gyanendraknojiya** [comment]
**npm i htmlparser2** works for me
