### ISSUE TITLE
I need to re `find` components between each `invoke` on them. 

### ISSUE THREAD

**Issue by dwjohnston** [enzymejs/enzyme#2406]
### Current behavior

This maybe related to the ['nested component may not be updated after state updates'](https://github.com/enzymejs/enzyme/blob/master/docs/common-issues.md#nested-component-may-not-be-updated-after-wrapper-updates) issue in the common issues - in which case the documentation there could  be updated. 

**Issue summary** 
If I have a function component using `useState` and `useCallback` hooks, and I am using `find` and `invoke` to trigger those memoised callbacks , then I need to `find` between each `invoke` otherwise the callbacks appear to lose track of the component state. 

```
function App(props) {
  const {onChange} = props; 
  
const [value, setValue]  = useState(''); 
  
const handleChange = useCallback(event => {
    setValue(event.target.value); 
  }, [setValue]); 

  const handleBlur = useCallback(() => {
    onChange(value); 

  }, [value, onChange]); 

  return (
    <div className="App">
      <header className="App-header">
        <input type = "text" onChange = {handleChange} onBlur = {handleBlur}/>
      </header>
    </div>
  );
}
```

```
test('This test works', () => {

  const mockChange = jest.fn(); 
  const wrapper = mount(<App onChange = {mockChange}/>); 

  const input = wrapper.find('input'); 
  input.invoke('onChange')(
    {target: {
    value: '1'}
    }
  ); 

  const input2 = wrapper.find('input');
  input2.invoke('onBlur')(null);   

  expect(mockChange).toHaveBeenCalledWith('1');
});


test('This test does not', () => {

  const mockChange = jest.fn(); 
  const wrapper = mount(<App onChange = {mockChange}/>); 

  const input = wrapper.find('input'); 

  input.invoke('onChange')(
    {target: {
    value: '1'}
    }
  ); 

  input.invoke('onBlur')(null);   

  expect(mockChange).toHaveBeenCalledWith('1'); // expected "1" received ""
});
```

Repro here: https://github.com/dwjohnston/jest-react-enzyme-sandbox/tree/enzyme-find-repro

### Expected behavior

I don't have to refind a component each time I am going to invoke something on it. (Or is there an easy way to do this for me)? 

### Your environment

Node v10.19.0
macOS 10.15.5

#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.11.0
| react               | 16.13.1
| react-dom           | 16.13.1
| react-test-renderer | N/A (create-react-app)
| adapter (below)     | 

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by dwjohnston** [comment]
I think I understand why this is happening - 

Basically when you do a `find` you get an immutable snapshot of that component at that point in time. 

So if you have later done a state update, and then your callbacks have been re-created, then that find still have reference to the old callbacks. 

I guess the question is - is there functionality in enzyme that allows some kind of updating of the 'find' objects - or as a rule of thumb should I just say 'always `find` immediately before you `invoke`' ?

**Comment by ljharb** [comment]
Every time there's a change, you have to re-find from the root. This is by design, see https://github.com/enzymejs/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#element-referential-identity-is-no-longer-preserved.

Basically, re-find from the root anything you expect anything to change, because otherwise, it won't.
