### ISSUE TITLE
Redux Connect + React.memo + shallow returns typeError

### ISSUE THREAD

**Issue by kblankenship1989** [enzymejs/enzyme#2407]
If you haven't found any duplicated issues, please report it with your environment!

### Current behavior
Shallow rendering of a component wrapped in `React.memo` that is connected to a store using `react-redux.connect` returns:  `TypeError: Cannot read property 'prototype' of undefined`.  Removing memo from the connected component fixes this issue, and removing connect fixes this as well but neither of these work with the needed implementation.
### Expected behavior
Shallow should successfully render during test, similar to if memo was removed.
#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.10.0
| react               | 16.10.1
| react-dom           | 16.10.1
| react-test-renderer | N/A
| adapter (below)     | 1.14.0
| react-redux      | 5.0.6

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by trhinehart-godaddy** [comment]
Ran into this error but with a different HOC. Updating `hoist-non-react-statics` resolved the issue.

**Comment by ljharb** [comment]
I'll close this then; @kblankenship1989 if updating hoist-non-react-statics doesn't fix your issue, I'll reopen.
