### ISSUE TITLE
Forced to shallow Find an element more than once to validate state updates

### ISSUE THREAD

**Issue by dschinkel** [enzymejs/enzyme#2409]
I'm not sure why I had to do what I deem a "hack" in this case for verifying the updated state of display after calling some of the public API methods on my component:

**So when I first wrote the test, I wrote it this way:**

```
test('handles multiple addition operations', t => {
  const calculator = shallow(<CalculatorUI />);
  const { equate, inputNumber, plus } = calculator.instance();
  const display = calculator.find('[data-testid="display"]');

  inputNumber('1');
  plus();
  inputNumber('2');
  t.is(display.props().displayResult, '2'); // this fails because it doesn't contain the updated state after I called inputNumber and plus()
  
 equate();
  plus();
  inputNumber('1');
  plus();
  inputNumber('2');
  plus();
  inputNumber('33');
  equate();
  t.is(display.props().displayResult, 39);
});
```

**The problem with this, is that display wasn't getting the updated state of 39 unless I wrote the test this way which feels gross to me:**
```
test('handles multiple addition operations', t => {
  const calculator = shallow(<CalculatorUI />);
  const { equate, inputNumber, plus } = calculator.instance();
  let display;

  inputNumber('1');
  plus();
  inputNumber('2');
  display = calculator.find('[data-testid="display"]'); // this is fine and does contain the updated state for some reason
  t.is(display.props().displayResult, '2');
 
  equate();
  plus();
  inputNumber('1');
  plus();
  inputNumber('2');
  plus();
  inputNumber('33');
  equate();
  display = calculator.find('[data-testid="display"]');
  t.is(display.props().displayResult, 39); // this also then passes as well
});
```

I don't know why.  Usually when I **shallow** something once, I'm able to perform multiple operations on a component and simply assert on the updated state after finding that thing (SUT) once only in my test...not having to re-find the item on the DOM multiple times for it to work.

https://github.com/dschinkel/calculator-kata

**Comment by ljharb** [comment]
That is very intentional, and was changed in v3. You always have to re-find from the root when anything changes: https://github.com/enzymejs/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#element-referential-identity-is-no-longer-preserved

**Comment by dschinkel** [comment]
ok good to know, I missed that update. Thanks!!
