### ISSUE TITLE
.simulateError is not a function

### ISSUE THREAD

**Issue by asingh04** [enzymejs/enzyme#2411]
I am trying to unit test my ErrorBoundary HOC and to throw an error from the wrapped component, I want to use the `.simulateError()` API as mentioned in the doc https://enzymejs.github.io/enzyme/docs/api/ReactWrapper/simulateError.html.

The ErrorBoundary HOC has simple implementation:

```javascript
const withErrorBoundary = (...args) => Component => {
    class ErrorBoundary extends React.PureComponent {
        componentDidCatch(...){
             // some logic
        }
       render() {
           // some render logic
           return (<Component ..../>);
       }
    }
    return hoistNonReactStatics(ErrorBoundary, Component);
};
export default withErrorBoundary;
```
In my unit test File
```javascript
import { mount } from 'enzyme';
import withErrorBoundary from './withErrorBoundary';

const MyComponent = () => (<div>Render</div>); 

it('Should Render Error Component', () => {
    const DecoratedComponent = withErrorBoundary()(MyComponent);
    const wrapper = mount(<DecoratedComponent />)

    expect(wrapper.find(MyComponent)).toHaveLength(1); // this passes

    wrapper.find(MyComponent).simulateError(new Error('Error While Rendering')); // this throws error
    // some validations
});
```
### Current behavior
The test throws an error with the message
```
TypeError: wrapper.find(...).simulateError is not a function
```

I also noticed in the prototype of `ReactWrapper` Object returned by `wrapper.find(MyComponent)`, `simulate` function is present but not the `simulateError` function.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.1.1.
| react               | 16.5.2
| react-dom           | 16.5.2
| react-test-renderer | ^16.0.0
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
You have a very old version of enzyme and the test renderer. Please upgrade to the latest enzyme, and the latest adapter version, and also make sure that the major and minor versions match of react, react-dom, and react-test-renderer.

**Comment by asingh04** [comment]
@ljharb Thanks for the response. I tried `yarn upgrade enzyme` but it still kept the library at v3.1.1 . I will try upgrading it to v3.11.0 and use the APIs.
