### ISSUE TITLE
Click Events and React Hook Local State

### ISSUE THREAD

**Issue by dschinkel** [enzymejs/enzyme#2413]
I feel this might be related to the fact that when you perform an action on a hook, that it creates a new instance of that hook altogether each time, so you lose the old reference, and hence you lose local state of your hook.

Anyway, not sure if this is related but after performing a series of actions, state is not retained.

```
test('handles an addition operation', t => {
  const calc = Calculator();
  calc.evaluate();
  const calculatorUI = mount(<CalculatorUIHooks2 calculator={calc} />);
  const oneKey = calculatorUI.find('[data-testid="numberKey1"]');
  const plusKey = calculatorUI.find('[data-testid="plus"]');
  const twoKey = calculatorUI.find('[data-testid="numberKey2"]');
  const equalskey = calculatorUI.find('[data-testid="equals"]');
  const display = calculator.find('[data-testid="display"]');

  oneKey.prop('onClick')();
  plusKey.prop('onClick')();
  twoKey.prop('onClick')();
  equalskey.prop('onClick')();

  t.is(display.props().displayResult, 3); // result is still 0 which is what it defaults to when a hook first runs
});

```

Part of the prod code it calls to give you some more context.  For example `oneKey.prop('onClick')();` ultimately calls `inputNumber()`.  Problem is each time I perform a click, I lose `combinedInput` state because the hook reference is lost most likely.

Eventually we set `displayResult` to use `combinedInput` later in the code.  But because `combinedInput` does not retain state, `displayResult` is set to `0` still due to that fact.
```
export const CalculatorUIHooks2 = (props) => {
  const [combinedInput, setCombinedInput] = useState('');
  const [displayResult, setdisplayResult] = useState(props.calculator.getResult());

  const inputNumber = (number) => {
    const currentInput = `${combinedInput}${number}`;
    const updatedDisplay = updateDisplayAfterInput(currentInput, number);

    setCombinedInput(currentInput);
    setdisplayResult(updatedDisplay);
  }
...
```

**Now, with enzyme, how do you resolve this issue?** 
(And TBH, I'd prefer shallow but in this case since hooks forces us to use button clicks to even test them as you can't expose any part of your closure, I had to use mount as Display is a sub component)

_Side: why when I post cod in an Enzyme issue is it formatting it with 4 or more spaces when my code's only got 2 spaces for tabs?  I had to correct it manually in this post_

**Comment by dschinkel** [comment]
Ah crap, dumb mistake

test('handles an addition operation', t => {
  const calc = Calculator();
  calc.evaluate();
  const calculatorUI = mount(<CalculatorUIHooks2 calculator={calc} />);
  const oneKey = calculatorUI.find('[data-testid="numberKey1"]');
  const plusKey = calculatorUI.find('[data-testid="plus"]');
  const twoKey = calculatorUI.find('[data-testid="numberKey2"]');
  const equalskey = calculatorUI.find('[data-testid="equals"]');

  oneKey.prop('onClick')();
  plusKey.prop('onClick')();
  twoKey.prop('onClick')();
  equalskey.prop('onClick')();
  const display = calculator.find('[data-testid="display"]');

  t.is(display.props().displayResult, 3);
});

**Comment by ljharb** [comment]
react provides no hooks for hooks, so there's no way for enzyme to interact with them.

If `simulate` works differently than invoking the prop directly, it's because react has provided an integration with react-test-renderer for simulating events (something I'm unaware of, and that never held true before)

**Comment by ljharb** [comment]
You may be missing a `calculatorUI.update()` call, but additionally, you must re-find from the root *every time* after a change is made. In other words, don't cache all your nKeys, call `.find` fresh every time.

**Comment by dschinkel** [comment]
Thanks @ljharb !  Yea I tried update() but strange things happened.  At least it works with simulate.
