### ISSUE TITLE
Can't .find() when ReactDOM.render() used

### ISSUE THREAD

**Issue by Nick-Zabalza** [enzymejs/enzyme#2416]
#### Issue

To start off, I've only been programing for half a year and this is my first bug submittal report. So hopefully you can have some patience with me.

Background:
I am in a software engineering bootcamp and am coding a service intended to work with a proxy that also consumes the services of my group members.

My service is entirely self-contained EXCEPT when a modal window pops up. In our proxy's index.html file, there is a div with id "MODAL_ATTACH_POINT" that all modal's have to attach to. And so, for my service's one modal, I attach it to that point with ReactDOM.render(). Then when the modal's close button is clicked, unmount it with ReactDOM.unmountComponentAtNode()

Which means ReactDOM.render() appears exactly twice in my code. Once for mounting the service's uppermost parent component and once for mounting this modal. All other times, components are mounted/unmounted as normal in React, based on Redux state since i am also using Redux.

Everything works fine in the browser.

The issue:
In my Jest/Enzyme tests, I am using mount(), not shallow().

I also temporaily add a div with id "MODAL_ATTACH_POINT" to the uppermost level of my service's component structure, as such:

```jsx
return (
      <div id="reviews-module" style={{ display: 'flex', flexDirection: 'column', flexShrink: '0' }}>
        {/*The tag directly below this is for testing purposes only. Make sure to comment out before building for production*/}
        <div id='MODAL_ATTACH_POINT' />
        <ReviewHeader />
        <ReviewBody />
        <Reviews />
      </div>
    );
```

I've written dozens of tests using Jest/Enzyme for this service already and they all pass. So I'm fairly confident my tests are written correctly.

I can also find my modal window when doing the following

```jsx
it('appears when the most favorable helpful review link is clicked in the HighlightedReviews component', () => {
      const wrapper = mount(<Provider store={store}><ReviewsModule /></Provider>, { attachTo: document.body });

      store.dispatch(updateReviewAverage(reviewAverage));
      store.dispatch(updateNumberOfReviews(numberOfReviews));
      store.dispatch(updateAllReviews(allReviews));
      wrapper.update();

      let renderedComponent = wrapper.render();
      let targetComponent = renderedComponent.find('#full-review-modal');

      expect(targetComponent).toHaveLength(0);

      wrapper.update();
      wrapper.find('#anchor-tag-most-favorable').simulate('click');
      wrapper.update();

      renderedComponent = wrapper.render();
      targetComponent = renderedComponent.find('#full-review-modal');

      expect(targetComponent).toHaveLength(1);

      wrapper.unmount();
    });
```

So the change IS happening when I simulate the click on the anchor tag that causes the modal to pop up. (Note that the modal is not an iframe...I am basically misusing the anchor tag at this point since it doesn't have an actually href). In other words, I can search for elements that appear only in my modal, in the rendered component (like above when I search for "#full-review-modal", which means renderedComponent.find() works perfectly fine).

What I cannot do is wrapper.find() or wrapper.findWhere() on any ids or styles or anything that appears in my modal andsits subtree. Whenever i do this (mostly so I can then simulate a click on the modal's close button), I get 0 nodes found. So the problem seems to me that, by using ReactDOM.render() to add components to my parent level DOM structure, this does actually add it in the Jest/Enzyme environment (as witnessed by those components being rendered), but does so in a way that the wrapper cannot find those elements with .find() or .findWhere().

Either this is a bug or it is intended and I am not using Jest/Enzyme in the intended manner. If it is the latter, what is the correct manner to test my modal's code(and thanks in advance for helping me)? If it is the former, thanks in advance for looking into this.

#### API
- [x ] mount

#### Version 

| library             | version
| ------------------- | -------
| enzyme              | 3.11.0
| react               | 16.13.1
| react-dom           | 16.13.1
| adapter (below)     | 

#### Adapter

- [ x] enzyme-adapter-react-16 V1.15.2

**Comment by Nick-Zabalza** [comment]
For some reason that first code block came out looking wierd. Also, I wasn't able to edit the comment. So here is that first code block again

return (
      <div id="reviews-module" style={{ display: 'flex', flexDirection: 'column', flexShrink: '0' }}>
        {/*The tag directly below this is for testing purposes only. Make sure to comment out before building for production*/}
        <div id='MODAL_ATTACH_POINT' />
        <ReviewHeader />
        <ReviewBody />
        <Reviews />
      </div>
    );

**Comment by ljharb** [comment]
Hi and welcome! I fixed your code blocks; use three backticks followed by `jsx`: ` ```jsx ` at the start, and ` ``` ` at the end, to get proper block syntax highlighting.

ReactDOM.render is definitely not supposed to be used inside your app - React has `createPortal` for modals now, and that's what i'd suggest you use :-)

**Comment by Nick-Zabalza** [comment]
I'll try that. Thanks!

**Comment by ljharb** [comment]
Happy to keep answering any questions you have :-)
