### ISSUE TITLE
Snapshot testing returning empty object with jest and preact

### ISSUE THREAD

**Issue by kanishk-anand-oyo** [enzymejs/enzyme#2417]
### Current behavior

`shallow` and `mount` are returning `ShallowWrapper{}` and `ReactWrapper{}` when used with jest and preact. I've used `enzyme-with-json` for serialization, which returns the expected result, but `expect` fails when used with `toMatchSnapshot` since it compares it with Empty Object.

``` import React from 'react';
import { shallowToJson } from 'enzyme-to-json';
import { shallow } from 'enzyme';
import Loader from './index';

describe('Loader Component', () => {
  it('should render correctly', () => {
    const component = shallow(<Loader />);
    console.log(component); // returns ShallowWrapper{}
    expect(shallowToJson(component)).toMatchSnapshot();
  });
});
```

### Expected behavior

The snapshot should return correct output of the contents of `<Loader />` component, and the test should pass. 

Content received by the test are : 
```
<div className="loader u-RTLPositive" style={Object {"width": "30px"}}>
      <svg className="loader__circular" viewBox="25 25 50 50">
        <circle className="loader__path" cx="50" cy="50" r="20" fill="none" strokeMiterlimit="10" />
      </svg>
 </div>
```

And Snapshot, to which it is compared is : `ShallowWrapper {}` 

### Your environment
"preact" : 10.3.3,
"jest": 26.0.1,
"jest-enzyme": 7.1.2
"enzyme-to-json": 3.5.0

Here's my setup file provided to Jest : 

``` 
import { configure } from 'enzyme';
import 'jest-enzyme';
import Adapter from 'enzyme-adapter-preact-pure';

configure({ adapter: new Adapter() });
```

#### API

- [✔️] shallow
- [✔️] mount
- [✔️] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.11.0
| react               | N/A
| react-dom           | N/A
| react-test-renderer | N/A
| adapter (below)     | 

#### Adapter

- [✔️ ] others (enzyme-adapter-preact-pure : 2.2.0 )

**Comment by ljharb** [comment]
enzyme doesn't support or recommend snapshot testing; the closest is `wrapper.debug()`. What's `component.debug()` print out?

**Comment by kanishk-anand-oyo** [comment]
@ljharb component.debug() prints the correct JSX content, same as `shallowToJson(component)`, but the matcher function seems to be returning `ShallowWrapper{}`
```
<div className="loader u-RTLPositive" style={Object {"width": "30px"}}>
      <svg className="loader__circular" viewBox="25 25 50 50">
        <circle className="loader__path" cx="50" cy="50" r="20" fill="none" strokeMiterlimit="10" />
      </svg>
 </div>
```

The output when running the test is : 
```
- Snapshot  -  1 (ShallowWrapper {})
+ Received  + 22 (the JSX above)
```

**Comment by ljharb** [comment]
Seems like this is an issue with toMatchSnapshot or enzyme-to-json, not with enzyme itself?

**Comment by cadence09** [comment]
I haven't used enzyme-to-json with toMatchSnapshot, but if you use toMatchSnapshot alone, it should works.

**Comment by cadence09** [comment]
I ran the test on my side, it passed it. I think you may need to delete the previous snapshot that saved in the src folder and then run the test again.

**Comment by saher-elgendy** [comment]
@cadence09 i have the same problem and i asked a question on stackoverflow here, i would be thankful if you could help
https://stackoverflow.com/questions/64003690/shallowwrapper-is-empty-testing-snapshot-jest-enzyme

**Comment by cadence09** [comment]
@saher-elgendy  I commented on your post. Let me know if it works.

**Comment by saher-elgendy** [comment]
@cadence09  thank you but i am trying for two days now, tried everything possible and the solution was just to press `u`  after the the snapshot fail in the first time!!!!!

**Comment by ljharb** [comment]
Since this seems to be an issue with whatever snapshotting tool you're using, and not with enzyme, I'll close this.

(I'd suggest avoiding snapshot testing - in practice, devs just end up rubber-stamping them, and they aren't actually testing things about your components that are important)
