### ISSUE TITLE
Typescript enzyme using `invoke` method with Event properties.

### ISSUE THREAD

**Issue by ashr81** [enzymejs/enzyme#2419]
I am trying to trigger the `invoke` method on a React component. This way
```
wrapper.find(TextField).invoke('onChange')({currentTarget: { value: 'approved'}});
```

Where TextField contains the `input` field inside it. I trigger `onChange` on these `input` using its parent component.
TextField looks like below:
```
const TextField = ({ onChange, value }: { value: string; onChange: (e:ChangeEvent<HTMLInputElement>) => void;}) => {
  return (<input onChange={onChange} value={value}>)
}
```
Does `enzyme` provide types for the custom events generated here:
because I am getting this error:
```
error TS2322: Type '{ value: string; }' is not assignable to type 'EventTarget & HTMLInputElement'.
      Type '{ value: string; }' is missing the following properties from type 'EventTarget': addEventListener, dispatchEvent, removeEventListener

wrapper.find(TextField).invoke('onChange')({ currentTarget: { value: 'approved' }});
```
I already installed `"@types/enzyme": "^3.10.5"` and `"enzyme": "^3.11.0",`
How do I resolve this error?

**Comment by ljharb** [comment]
enzyme doesn't provide any types; i'd assume that the DT v3.10 package lacks the types for things added in v3.11. Filing an issue there might be best.
