### ISSUE TITLE
enzyme-shallow-equal 1.0.3 has a runtime dependency on @babel/runtime but does not list it in package.json

### ISSUE THREAD

**Issue by D4N14L** [enzymejs/enzyme#2427]
### Current behavior
When running Jest:
```
##[error]    Cannot find module '@babel/runtime/helpers/interopRequireDefault' from 'index.js'
##[error]
##[error]    Require stack:
##[error]      D:/dbs/Cx/osct/rush-temp/node_modules/.onedrive.pkgs.visualstudio.com/enzyme-shallow-equal/1.0.3/node_modules/enzyme-shallow-equal/build/index.js
...
````

### Expected behavior

No error when running Jest

### Your environment

Node 10, Jest 25.5.1

#### API

- [x] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 
| react               | 
| react-dom           | 
| react-test-renderer | 
| adapter (below)     | enzyme-adapter-react-16

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
whoops, thanks! let me get a fix out asap

**Comment by ljharb** [comment]
v1.0.4 will be released once [tests](https://travis-ci.com/github/enzymejs/enzyme/builds/178829171) pass.

**Comment by sachinjoseph** [comment]
@ljharb question - is enzyme-shallow-equal not published from master anymore?

**Comment by ljharb** [comment]
@sachinjoseph it is; i'm just in the middle of a bunch of package publishes, so i've only been pushing up the tags as i publish. After this one's done, i'll push everything up to master to close the issue.

**Comment by sachinjoseph** [comment]
@ljharb thank you! just wanted to clarify.

**Comment by ljharb** [comment]
v1.0.4 is out, and v1.0.2 and v1.0.3 are both deprecated.
