### ISSUE TITLE
ShallowWrapper instance() method always returns null since 1.15.3

### ISSUE THREAD

**Issue by cascornelissen** [enzymejs/enzyme#2434]
Looks like this change broke the `.instance()` method on a `shallow()` rendered component for us when the root component is a `React.Suspense`. Verified to be working correctly in `enzyme-adapter-react-16@1.15.2`.

```
const wrapper = shallow(<ClassComponentWithReactSuspense />);
wrapper.instance(); // Always null
```

Any ideas?

----

It does seem to work correctly when using `mount()` though.

_Originally posted by @cascornelissen in https://github.com/enzymejs/enzyme/pull/2328#issuecomment-673513981_

**Comment by joshuablokland** [comment]
I have the same issue as well!

**Comment by cascornelissen** [comment]
Tagging @ljharb and @lamhieu-vk to make sure they're aware multiple people are running into this.

**Comment by lamhieu-vk** [comment]
Sorry for the late reply. I will debug, report, and fix it soon!

**Comment by lamhieu-vk** [comment]
@cascornelissen can you provide me a reproduce repository?

**Comment by cascornelissen** [comment]
@lamhieu-vk, I had a notification about a reply on this thread asking for repro repo but since that message is not visible here I guess you’ve found the issue and don’t need a repro anymore?

**Comment by lamhieu-vk** [comment]
@cascornelissen I created repro repo for this bug

**Comment by lamhieu-vk** [comment]
I created a pull request for this issue!

**Comment by cascornelissen** [comment]
@ljharb, sorry to tag you but are there any plans for a new patch release? We'd really like to get this fixed in our projects. 😅 

Also, thanks for your time working on OSS! ❤️

**Comment by ljharb** [comment]
v1.15.4 is released.

**Comment by lamhieu-vk** [comment]
@cascornelissen please verify the new version and confirm here 😉

**Comment by cascornelissen** [comment]
Thanks for the release, it does indeed fix it on our projects. Thanks to both of you once more!
