### ISSUE TITLE
Simulate changes is always based on initial state and does not consider previous state

### ISSUE THREAD

**Issue by RyanLinXiang** [enzymejs/enzyme#2435]
### Current behavior

I am new to testing and I have a question on Enzyme which kept me busy all day. I try to reduce the complexity of my problem and break down into just two input fields: Suppose I have two input fields ("street" and "housenumber"). In my REACT app whenever one of these fields get updated, the state is also updated via useReducer:

```
initial state = {
 street: "",
 housenumber: ""
}
```

Now the change handler calls the reducer and updates the state every time relying on the previous state :

```
new state value on every change = {
...prevState,
street: "newValue" OR housenumber: "newValue" depends on what input field has changed
}
```

The change handler also passes on the state to a parent component:

```
parentFunction(state);
```

This is where my testing comes in. I hook into the parentFunction and stimulate a change in both fields:

```
wrapper.find('#street').simulate("change", {...});
wrapper.find('#housenumber').simulate("change", {...});
```

At the end I expect in the last call, that my state is updated with both new values:

```
expect(parentFunction).toHaveBeenLastCalledWith(
 {
  street: newValue, 
  housenumber: newValue
 }
)
```

But the test fails and here comes the problem: I don't understand why the second change (to the "housenumber" field) does not consider the first change (to the "street" field)? JEST says that it received the parent function has been called with the following value instead:

```
{
 street : "", // initial value 
 housenumber : newValue
}
```

It seems that "simulate" does not consider previous state changes and works with the initial state instead. I also splitted both "simulate" changes into separate tests - no difference. Can someone give me more background info on this? Is there a workaround? Thank you very much!

BR

### Expected behavior

state changes should be saved and considered whenever a new change simulate is triggered and handled which depends on previous state. 

#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.11.0
| react               |  16.13.1
| react-dom           |  16.13.1
| react-test-renderer | 
| adapter (below)     |  1.0.6

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
@RyanLinXiang did you figure it out?

**Comment by RyanLinXiang** [comment]
Yes! It was not an Enzyme issue but due to the nature how my code worked. I didn't know why I missed that.
