### ISSUE TITLE
enzyme.mount  with jsdom v16 throws TypeError: Illegal invocation

### ISSUE THREAD

**Issue by ingvar-snow** [enzymejs/enzyme#2437]
It loooks like Enzyme doesn't work with jsdom v16.

I use Jest + Enzyme  + jsdom.
Jsdom setted up by this instruction:
https://github.com/enzymejs/enzyme/blob/master/docs/guides/jsdom.md

I try to run test that doesn't do nothing, only mount a react element.
```
test('me test', () => {
  const wrapper = enzyme.mount(<div>test</div>);
});
```

It worked fine with jsdom v15. But after update to jsdom v16 it fails with "TypeError: Illegal invocation"

#### My environment

| library             | version
| ------------------- | -------
| enzyme              | 3.11.0
| react               | 16.8.6
| react-dom           | 16.8.6
| adapter     | enzyme-adapter-react-16 1.15.3

**Comment by jmlavoier** [comment]
@ingvar-snow exactly the same here, did you get a solution?

**Comment by jmlavoier** [comment]
#### devDependencies: 
```
"@babel/cli": "^7.11.6",
    "@babel/core": "^7.11.6",
    "@babel/preset-env": "^7.11.5",
    "@babel/preset-react": "^7.10.4",
    "babel-jest": "^26.3.0",
    "coveralls": "^3.0.9",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.4",
    "eslint": "^7.9.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jest": "^23.0.4",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-react-hooks": "^2.3.0",
    "jest": "^26.4.2",
    "jsdom": "^16.4.0",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
```
#### setup.js
```
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import { JSDOM } from 'jsdom';

configure({ adapter: new Adapter() });


const jsdom = new JSDOM('<!doctype html><html><body></body></html>');
const { window } = jsdom;

function copyProps(src, target) {
  Object.defineProperties(target, {
    ...Object.getOwnPropertyDescriptors(src),
    ...Object.getOwnPropertyDescriptors(target),
  });
}

global.window = window;
global.document = window.document;
global.navigator = {
  userAgent: 'node.js',
};
global.requestAnimationFrame = function requestAnimationFrame(callback) {
  return setTimeout(callback, 0);
};
global.cancelAnimationFrame = function cancelAnimationFrame(id) {
  clearTimeout(id);
};
copyProps(window, global);
```

#### 
```
 TypeError: Illegal invocation

      59 |     };
      60 |
    > 61 |     const wrapper = mount(<Wrapper />);
         |                     ^
      62 |     wrapper.unmount();
      63 |
      64 |     expect(window.document.removeEventListener).toHaveBeenCalled();

      at HTMLDivElement.get nodeType [as nodeType] (node_modules/jsdom/lib/jsdom/living/generated/Node.js:460:15)
      at isValidContainer (node_modules/react-dom/cjs/react-dom.development.js:24640:27)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:24826:8)
      at getFiber (node_modules/enzyme-adapter-react-16/src/detectFiberTags.js:14:12)
      at detectFiberTags (node_modules/enzyme-adapter-react-16/src/detectFiberTags.js:76:15)
      at ReactSixteenAdapter.createMountRenderer (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:455:19)
      at ReactSixteenAdapter.createRenderer (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:810:51)
      at new ReactWrapper (node_modules/enzyme/src/ReactWrapper.js:113:32)
      at mount (node_modules/enzyme/src/mount.js:10:10)
      at Object.<anonymous> (tests/index.js:61:21)
```

**Comment by jmlavoier** [comment]
Has a long time since I've created my jest `setup.js`, and I set that with `jsdom` as described in the documentation about `mount` requires `jsdom`.

```js
const jsdom = new JSDOM('<!doctype html><html><body></body></html>');
const { window } = jsdom;

function copyProps(src, target) {
  Object.defineProperties(target, {
    ...Object.getOwnPropertyDescriptors(src),
    ...Object.getOwnPropertyDescriptors(target),
  });
}

global.window = window;
global.document = window.document;
global.navigator = {
  userAgent: 'node.js',
};
global.requestAnimationFrame = function requestAnimationFrame(callback) {
  return setTimeout(callback, 0);
};
global.cancelAnimationFrame = function cancelAnimationFrame(id) {
  clearTimeout(id);
};
copyProps(window, global);
```

I believe that it used to solve a problem that was happening with the enzyme's versions before `3.11.0` and right now isn't happening anymore. 

I removed that `jsdom` configuration from my `setup.js` and my test ran well.

**Comment by ljharb** [comment]
@ingvar-snow i was able to use your repo and reproduce the issue, thanks!

The issue is indeed related to the JSDOM code, because you're using jsdom 16 - if you downgrade to jsdom v10-v15, everything works fine.

**Comment by javierfernandes** [comment]
> @ingvar-snow i was able to use your repo and reproduce the issue, thanks!
> 
> The issue is indeed related to the JSDOM code, because you're using jsdom 16 - if you downgrade to jsdom v10-v15, everything works fine.

Does this mean that the setup code is not necessary anymore when using enzyme with JSDOM 16 ?

Thanks !

**Comment by ljharb** [comment]
No, it's still necessary - it means that jsdom 16 has either a breaking change or a bug, and nobody's yet figured out and shared the proper setup code that works with it.

**Comment by MilosRasic** [comment]
I know it's a closed issue but just sharing a possible easy workaround.

We have a mixed enzyme/RTL setup and we're using @testing-library/jest-dom to set up mock DOM.

Simply plop `import '@testing-library/jest-dom'` in your setup.js, remove your manual jsdom import and `window` mocking, and it should work fine. It's a dev dependency so it won't increase your bundle size or anything like that.
