### ISSUE TITLE
Not able to get to actions via props() via shallow

### ISSUE THREAD

**Issue by dschinkel** [enzymejs/enzyme#2449]
**prior to redux 7:**
```js
it('contains expected actions', () => {
  const homePage = shallow(<HomePageContainer store={store} />);
  
 expect(homePage.props().fetchFeaturedCompanies).to.exist;
  expect(homePage.props().fetchCompanies).to.exist;
});
```

**after Redux 7** I don't think you can just pass in store as a prop anymore.  I thought that they added back that ability?  I don't remember where they landed with that.

So since I was getting an error that store is not a property, I had to wrap this in a garbage provider to even get this to compile again after upgrading Redux:

But after doing so, TS complains that **store** is **not a prop**:
```js
it('contains expected actions', () => {
  const homePage = shallow(<Provider store={store}><HomePageContainer /></Provider>);

  expect(homePage.props().fetchFeaturedCompanies).to.exist;
  expect(homePage.props().fetchCompanies).to.exist;
});
```

`expected undefined to exist`

Here's yet another old test that tries to get to an action via props
```js
  it('fetches companies', async () => {
    mockGet('/api/v1/companies', {});

    const homePage = shallow(<HomePageContainer store={store} />);
    await homePage.props().fetchCompanies();
    const newState = store.getState();

    expect(newState.company.companies).to.exist;
    expect(newState.company.featuredCompanies).to.not.exist;
  });
```
so it no longer is able to get at props this way or something after Redux 7?

Sigh it's been a while, totally forgot this thread https://github.com/reduxjs/react-redux/issues/1161

can anyone fill me in on the above, if this is even possible in Redux 7 both sending in a store as a prop and also being able to access actions like this as my existing tests were doing with props()?

My preference is:
- not to go through UI wiring like button clicks
- not to use mount

I like testing the surface area via props.

**Comment by ljharb** [comment]
TS isn't JS, and enzyme ships no types, so any type system errors are wildly out of scope of this project.

**Comment by dschinkel** [comment]
So this isn't a TS issue. I worded this wrong.

**Comment by ljharb** [comment]
You want:
```jsx
const homePage = shallow(<HomePageContainer />, {
  wrappingComponent: Provider,
  wrappingComponentProps: { store },
});
```

**Comment by dschinkel** [comment]
tried that and got 
`Error: Could not find "store" in the context of "Connect(HomePageContainer)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> `

**Comment by ljharb** [comment]
`{ store: dummyStore }`, probably?

In this case tho, you're using `connect`, so i think you don't pass a store at all, you just use `.dive()`.

**Comment by dschinkel** [comment]
I really truly do hate TS 👿
```js
it('contains expected actions', () => {
  const homePage = shallow(<HomePageContainer />).dive();

  expect(homePage.props().fetchFeaturedCompanies).to.exist;
  expect(homePage.props().fetchCompanies).to.exist;
});
```
TSError: ⨯ Unable to compile TypeScript:
src/test/unit/components/homepage/Home.spec.tsx(57,27): error TS2339: Property 'fetchFeaturedCompanies' does not exist on type 'Readonly<{}> & Readonly<{ children?: ReactNode; }>'.
src/test/unit/components/homepage/Home.spec.tsx(58,29): error TS2339: Property 'fetchCompanies' does not exist on type 'Readonly<{}> & Readonly<{ children?: ReactNode; }>'.
```

**Comment by dschinkel** [comment]
closing it, thanks for your efforts @ljharb I'm spent.

**Comment by ljharb** [comment]
TS has nothing to do with it. Figure out what makes your tests pass, and then use ts-ignore as needed until the real code passes the typecheck.

**Comment by dschinkel** [comment]
Like I said this code was working just fine.  The real questions had to do with Enzyme + React-Redux 7 combo

**Comment by dschinkel** [comment]
went back to ignoring TS and trying store as prop again:
```js
it('contains expected actions', () => {
  // @ts-ignore
  const homePage = shallow(<HomePageContainer store={fakeStore(
    {
      country: {
      countriesReceived: true,
      countries: [countryStub]
    },
    companies: {
      companiesReceived: true,
      companies: [companyStub],
    }
  }
)}/>);

  expect(homePage.props().fetchFeaturedCompanies).to.exist;
  expect(homePage.props().fetchCompanies).to.exist;
});
```
**AssertionError**: `expected undefined to exist`

So for some reason `.props()` no longer works and this worked fine before I changed up my Container and before upgrading to Redux 7.

**Comment by dschinkel** [comment]
I also just verified with the Redux team that store as a prop was re-introduced in React-Redux v7.  So that leaves us with a possible enzyme issue here when it can't find that prop anymore on the surface area of the shallowed component?

**Comment by dschinkel** [comment]
the fix: `expect(homePage.childAt(0).props().fetchFeaturedCompanies).to.exist;` and this is related to changes in react-redux how connect wraps stuff.  I knew this wasn't just me.

**Comment by ljharb** [comment]
enzyme - like all runtime javascript code - doesn't know about, see, or care about type notations. Adding anything in type-space should have no impact on value-space.

Glad you found a fix.

**Comment by dschinkel** [comment]
so the real problem was how you have to access things through Redux now via v6 or 7.  I had to add childAt(0) now to my examples above.

Also to get rid of the issue of TS complaining about store is not a recognized prop from tests, I added a **test.d.ts** file to my test folder with:
```js
declare namespace JSX {
	interface IntrinsicAttributes {
		store: any;
	}
}
```
in package.json, then reference it:
`"types": "src/test/test.d.ts",`

**Comment by QasimRRizvi** [comment]
When I do this
```
wrapper = shallow(<Login />, {
   wrappingComponent: Provider,
   wrappingComponentProps: {store}
 });
```
It generates error
```
Could not find "store" in the context of "Connect(LoginBase)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(LoginBase) in connect options.
```
Any fix for this
Note: store is 
```
store = mockStore({
   "authReducer": {
     isLoading: false,
   },
   login: () => {},
 });
```

**Comment by miteshdhaduk** [comment]
The same issue found. Not able to pass the store props in redux Provider.

Did anyone get any solution?

**Versions:**
react-redux: 7.2.2
next-redux-wrapper: 6.0.2
