### ISSUE TITLE
Shallow Render Trips on Link with React-Router Link far down in Component Tree

### ISSUE THREAD

**Issue by dschinkel** [enzymejs/enzyme#2451]
I'm shallow rendering a component:
```js
  beforeEach(() => {
    interview = shallow(<InterviewContainer store={fakeStore({ company: { company: null } })} />);
  });
```
This results in the error `Cannot read property 'prototype'​ of undefined`

Stack Trace:
```
TypeError: Cannot read property 'prototype' of undefined
    at isStateful (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:414:20)
    at wrapPureComponent (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:570:13)
    at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:688:30)
    at withSetStateAllowed (node_modules/enzyme-adapter-utils/src/Utils.js:99:18)
    at Object.render (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:687:20)
    at new ShallowWrapper (node_modules/enzyme/src/ShallowWrapper.js:411:22)
    at Object.shallow (node_modules/enzyme/src/shallow.js:10:10)
    at Context.<anonymous> (src/test/unit/components/interview/interview.container.spec.tsx:15:23)
    at processImmediate (internal/timers.js:456:21)
```

What resolves it is:
```js
  beforeEach(() => {
    interview = shallow(<Router><InterviewContainer store={fakeStore({ company: { company: null } })} /></Router>);
  });
```

`InterviewContainer` renders child `Interview` component.  `Interview` renders more children, one of which ultimately renders a react-router <Link> component.

What's odd here is that shallow doesn't render the full tree of children.  So why do I get the issue of having to wrap this in `<Router>` which is usually only needed when a component you are rendering contains React Router `<Link>`?  If I am shallow rendering, it shouldn't care about <Link> if it's not in the immediate component being shallowed correct?

Here's **InterviewContainer**:

```js
import React, { Component } from 'react';
import { connect, ConnectedProps } from 'react-redux';
import { fetchCompany } from '../actions/company/CompanyAsyncActions';
import Interview from './Interview';
import { RootState } from '../store';
import { RouteComponentProps, withRouter } from 'react-router';

class InterviewContainer extends Component<PropsFromRedux & RouteComponentProps<{ companyId: string }>> {
  componentDidMount() {
    const { fetchCompany } = this.props;
    const { companyId } = this.props.match.params;
    fetchCompany(companyId);
  }

  render() {
    const { company } = this.props;
    return (company && <Interview className="ft-interview" company={company} />) || null;
  }
}

const mapState = (state: RootState) => ({
  company: state.company.company
});

const mapDispatch = {
  fetchCompany
};

const connector = connect(
  mapState,
  mapDispatch
);

type PropsFromRedux = ConnectedProps<typeof connector>
export default withRouter(connect(mapState, mapDispatch)(InterviewContainer));
```

**Comment by ljharb** [comment]
I'd expect `Router` to be passed in via `wrappingComponent`, not directly wrapping the element being shallow tested.

What happens if you try that?

**Comment by dschinkel** [comment]
Is `wrappingComponent` something new?  

Same error:
```js
    interview = shallow(<InterviewContainer store={fakeStore({ company: { company: null } })} />,
      {
        wrappingComponent: Router,
        wrappingComponentProps: { store: fakeStore({ company: { company: null } }) }
      });
```

**Comment by dschinkel** [comment]
what's also bizarre is that after I rid that error by wrapping with <Router /> using the first method, this assertion fails.  I tried a couple different things here:
`const interview = shallow(<Router><InterviewContainer store={store} /></Router>).dive().find(".ft-interview");`
also tried:
`const interview = shallow(<Router><InterviewContainer store={store} /></Router>).childAt(0).find(".ft-interview");`

```
  it("contains an interview component", () => {
    const interview = shallow(<Router><InterviewContainer store={store} /></Router>).find(".ft-interview");
    expect(interview.length).to.equal(1);
  });
```

**Comment by ljharb** [comment]
It's been around for a number of versions. It's suddenly the "thing to do" because it was always conceptually wrong, and awkward, to be forced to wrap "not the thing you're testing" just to inject context. In other words, you're still "just able to wrap them", but that was always an inferior approach, so now we have a better one.

What is `interview.debug()`, in any of your examples?

**Comment by dschinkel** [comment]
I don't know cause it blows up before I can do that debug.

**Comment by dschinkel** [comment]
I don't know I guess lets get back to the initial question which is why shallow is even having issues with Link when Link is way down the tree

**Comment by dschinkel** [comment]
Sigh, I thought it was related to Link.  For some reason it's not, I could have sworn I commented out the child component using Link and didn't need Router but I do need Router probably because `InterviewContainer` is using withRouter.

Closing this. Thanks
