### ISSUE TITLE
TypeError: this._getEventHandlerFor is not a function

### ISSUE THREAD

**Issue by savv** [enzymejs/enzyme#2456]
### Current behavior
This is a duplicate of https://github.com/enzymejs/enzyme/issues/2436, but for a different environment.  Downgrading to jest@24.9.0 makes this issue go away. Upgrading to >=25, makes this issue surface, but this seems to be because it seems I get an older version of https://github.com/jsdom/jsdom

#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | ^3.11.0
| react               | 16.13.1
| react-dom           | ^16.13.1
| react-test-renderer | 16.13.1
| adapter (below)     | ^1.15.5

#### Adapter

- [X] enzyme-adapter-react-16

**Comment by ljharb** [comment]
What version of jsdom are you using? What exact error are you getting, on what code? What jest config are you using, including any setup code?

**Comment by savv** [comment]
> What version of jsdom are you using?

16.4.0

The thing that causes this is upgrading jest from 24.9.0 to 26.5.2 (or 25..). My guess is that it has to do with the transitive jsdom dependencies.

> What exact error are you getting, on what code?

I get the same error as in https://github.com/enzymejs/enzyme/issues/2436. It's unclear from the stack trace where it happens, but it seems to be during setup:
```
  ● Test suite failed to run

    TypeError: this._getEventHandlerFor is not a function

      at Object.get (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:86:26)
          at Array.forEach (<anonymous>)
```


> What jest config are you using, including any setup code?

The setup code is exactly the same as in https://github.com/enzymejs/enzyme/issues/2436

My jest config is: 
```
{
    "preset": "react-native",
    "transformIgnorePatterns": [
      "/node_modules/(?!native-base)/"
    ],
    "testMatch": [
      "**/test_*.ts",
      "**/test_*.tsx"
    ],
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/common/"
    ],
    "setupFiles": [
      "<rootDir>/testing/setup.js",
      "./node_modules/react-native-gesture-handler/jestSetup.js"
    ]
  }
```

**Comment by ljharb** [comment]
If you're getting an error from inside jsdom, then that's a bug in jsdom that you should file there.

Specifically for react-native, though, there doesn't yet exist a react-native adapter for enzyme, and you're using a react _web_ adapter. #1436 tracks a proper adapter.

**Comment by savv** [comment]
Thanks, I'm aware of all this. I would be great to use this new adapter when it's ready, but in the meantime enzyme seems to recommend this approach, [here](https://enzymejs.github.io/enzyme/docs/guides/react-native.html).

I just noticed that the recommended configuration changed. I will try that.
