### ISSUE TITLE
Not getting updated state when Mounting React Hook

### ISSUE THREAD

**Issue by dschinkel** [enzymejs/enzyme#2457]
I can't keep track of what Enzyme supports or doesn't anymore.  So I don't know if I expect this to even work at all with Enzyme TBH.

But here is my issue:

```js
it.only("shows featured companies listed by name", async () => {
  const newCompanies = [...companies];
  mockPostGraphQL("/graphql", query, newCompanies);

  const featuredCompanies = mount(<featuredCompanies />);
  const companies = findAttribute(featuredCompanies, "company");

  expect(companies.length).to.equal(5);
});
```

**FeaturedCompanies.tsx**
```js
const FeaturedCompanies = () => {
  const [featuredCompanies, setData] = useState([]);

  useEffect(() => {
    const fetchCompanies = async () => {
      const companies: Array<Company> = await findFeaturedCompanies();
      setData(companies);
    };

    fetchCompanies();
  }, []);

  return (
    <>
      <Companies companies={featuredCompanies} />
    </>
  );
};
```

it seems to be running my `expect()` before the async is finished fetching companies so the test fails too early as there are no companies yet.  I'm resolving async calls with await on the prod code side, and I don't see any where in my test or otherwise that I'm missing an await.

**Comment by dschinkel** [comment]
disregard, my fetch was malformed.  It works.

**Comment by ljharb** [comment]
This is the nature of JavaScript. `fetchCompanies` produces a Promise. Your test can't possibly reliably assert things after that promise has resolved, unless it *has access to* the promise and can await it.

The solution is to mock out `findFeaturedCompanies`, and await *that* in your test after the effect is started, and then you'll be able to call `wrapper.update()` and test the results.

**Comment by dschinkel** [comment]
What do you mean by `after the effect is started`

**Comment by ljharb** [comment]
Yes, hooks change the model drastically.

The issue is that your *test* runs long before `fetchFeaturedCompanies` is finished. You have to await it again because `await` doesn't "sleep" or block the thread, it's just sugar for a promise `.then`.

**Comment by ljharb** [comment]
In other words, there is no "lifecycle" of your component that's observable by *anything*, including React. React just updates whenever you effect *happens* to complete, and doesn't run anything afterwards. Your test can't know when it happens to complete unless you have something to await.

**Comment by dschinkel** [comment]
Ok just trying to figure out how to put that await in there somewhere in my test...this is weird.

`wrapper.update()` - why?

**Comment by ljharb** [comment]
Because enzyme has no way of knowing when the react render tree has updated - `wrapper.update` tells enzyme to check again.

**Comment by ljharb** [comment]
Yes, with classes, the lifecycle happens through observable invoked methods. With hooks, there is no lifecycle whatsoever - components just rerender when needed, and due to the nature of the JS language itself, it's *impossible* to observe closed-over things, and so there's no way to test these kinds of changes without coupling tests to implementation details.

**Comment by dschinkel** [comment]
Ok right, so if I can't get to `fetchCompanies` via props on a Hook now due to closure, how the heck am I going to await `fetchCompanies`?   It's called internally via closure.  So not sure how I can await something I can't get to, you know what I mean?

**Comment by ljharb** [comment]
Yes, exactly. You can use jest's module mocking to spy on it, but otherwise, you'd have to rearchitect.

**Comment by dschinkel** [comment]
Yea I'd prefer not to use a mocking framework.  But I'll have to rearchitect and hopefully share what I come up with!

**Comment by ljharb** [comment]
Sounds good, thanks. Will close in the meantime.
