### ISSUE TITLE
Cannot simulate kyedown jest enzyme, then fetch error: cannot read property 0 of undefined

### ISSUE THREAD

**Issue by namlq93** [enzymejs/enzyme#2459]
My code: 

    beforeEach(async () => {
        ....
        await act(async () => {
            wrapper = mount(<TestContainer />);
        });
    });

    test('Test search account', async () => {
        await wrapper
            .find('input[data-testid="search-account"]')
            .simulate('change', {
                target: { value: 'testQuery' },
            });
    
        await act(async () => {
            await wrapper
                .find('input[data-testid="search-account"]')
                .simulate('keydown', { key: 'Enter' });
        });
    
        expect(fetchMock.mock.calls[1][0]).toBe(
            '/api/v1/ca/accounts?page=0&search=testQuery',
        );
    });

I've got an error: "TypeError: Cannot read property 0 of undefined". It seems the keydown event has not been simulated.

![Screen Shot 2020-10-15 at 15 54 32](https://user-images.githubusercontent.com/41458989/96112968-a3adcd00-0f0d-11eb-9111-d71eb90a8128.png)

**Comment by namlq93** [comment]
Because I use only onKeyDown event on input, but I still simulate onChange

**Comment by ljharb** [comment]
I'd suggest avoiding `simulate` entirely; it doesn't faithfully simulate anything. If you want to invoke the onChange prop, use `.invoke('onChange')(fakeEvent)`.
