### ISSUE TITLE
@types/enzyme Cannot find namespace 'cheerio'

### ISSUE THREAD

**Issue by Clumsy-Coder** [enzymejs/enzyme#2468]
### Current behavior
Using command `tsc --build tsconfig.json .` returns the following error

![image](https://user-images.githubusercontent.com/19594044/98424016-a784c900-204d-11eb-97b8-78ff80e3f6ed.png)

### Your environment
React native project using Typescript `^4.0.5`

**react-native**: 0.63.3
**@types/enzyme**: ^3.10.8

#### Version

| library             | version
| ------------------- | -------
| enzyme              | ^3.11.0
| react               | 16.13.1
| **react-native**   | 0.63.3
| react-dom           | ^16.13.1
| react-test-renderer | ^16.13.1
| adapter (below)     | ^1.15.5

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Do you have @types/cheerio installed? Those would be required if DT had a sensible dependency system.

**Comment by Clumsy-Coder** [comment]
@ljharb No I don't. I thought it would be included in @types/enzyme npm package

**Comment by ljharb** [comment]
Unfortunately, it can’t, due to the way DT is designed. You’ll have to include them manually.
