### ISSUE TITLE
npm can't create-react-app

### ISSUE THREAD

**Issue by Jb-hub-sudo** [enzymejs/enzyme#2469]
### Hello Ma'am/ Sir I I'm just a beginner can you help me to fix this.

C:\Users\$^The_King^$>npx create-react-app myapp
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\$The_King$\AppData\Roaming\npm\node_modules\create-react-app\index.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by ljharb** [comment]
Hi there - unfortunately this repo is for enzyme, a react testing framework, and not a general help channel. I'd suggest IRC, a public Slack community, or StackOverflow, for more general help.
