### ISSUE TITLE
my expect function has no "to" object like "to.have.length"

### ISSUE THREAD

**Issue by kimkyeseung** [enzymejs/enzyme#2479]
my expect function has no "to" object like "to.have.length" but methods like "toHaveLength" or "toEqual".. why???

when I watching tutorial or examples of enzyme,
I can see a samples like this

```js
it('includes 1 div with class foo', () => {
	expect(wrapper.find('div.foo')).to.have.lengthOf(1);
})
```

but my expect function has no "to" object.. but just methods like "toEqual"..?

shoud I replace my expect function of jest???

**Comment by ljharb** [comment]
All of enzyme's tutorials are written using chai. If you're using jest, you'll have to modify them to match jest's matcher syntax (which i don't use, so I'm not sure what the equivalent would be)

**Comment by kimkyeseung** [comment]
That must be it. All of enzyme's tutorials are written using **chai**. I got it. thanks
