### ISSUE TITLE
After upgrade 

### ISSUE THREAD

**Issue by psaravanan** [enzymejs/enzyme#2484]
#### API

- [ ] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 
| react               | 
| react-dom           | 
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [ ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Please fill out the entire issue template, and I'll be happy to reopen.

**Comment by ljharb** [comment]
Looks like this is duplicated by #2485.
