### ISSUE TITLE
Enzyme fails to install

### ISSUE THREAD

**Issue by jpbulman** [enzymejs/enzyme#2487]
I'm currently running the recommended installation script 
```
npm i --save-dev enzyme enzyme-adapter-react-16
```
, but am getting the following error 
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for cheerio-select@cheeriojs-cheerio-select-master.tar.gz-art-external.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cheerio'
npm ERR! notarget
```

I don't recall ever installing cheerio, and it doesn't appear in my package.json. Is this possibly a problem with enzyme in the npm registry? I'm not sure how to go about fixing this.

**Comment by ljharb** [comment]
enzyme does include cheerio, but we're not responsible for it. Looks like cheerio was published an hour ago, and has an issue filed: https://github.com/cheeriojs/cheerio/issues/1576

**Comment by jpbulman** [comment]
Thanks! I wasn't sure if this was originating from Cheerio or if this was Enzyme trying to fetch a non existent version of Cheerio. I'll follow along the discussion there
