### ISSUE TITLE
Which version to use with react 16.13.1

### ISSUE THREAD

**Issue by callmekatootie** [enzymejs/enzyme#2488]
### Current behavior

Trying to install this module for reactjs version 16.13.1

When I try to install `enzyme-adapter-react-16.3` version, I get the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: Redacted@0.0.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"~16.3.0-0" from enzyme-adapter-react-16.3@1.7.3
npm ERR! node_modules/enzyme-adapter-react-16.3
npm ERR!   enzyme-adapter-react-16.3@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

and when I try to install `enzyme-adapter-react-16`, I get the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: Redacted@0.0.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@"^16.0.0-0" from enzyme-adapter-react-16@1.15.5
npm ERR!   node_modules/enzyme-adapter-react-16
npm ERR!     enzyme-adapter-react-16@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.14.0" from react-dom@16.14.0
npm ERR! node_modules/react-dom
npm ERR!   dev react-dom@"^16.13.1" from the root project
npm ERR!   peer react-dom@"^16.0.0-0" from enzyme-adapter-react-16@1.15.5
npm ERR!   node_modules/enzyme-adapter-react-16
npm ERR!     enzyme-adapter-react-16@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Which version do I thus install for react 16.13.1?

### Expected behavior

I should not get an error when I try to install `enzyme-adapter-react-16.3` for use with reactjs 16.13.1

#### Version

| library             | version
| ------------------- | -------
| enzyme              | ^3.11.0
| react               | 16.13.1
| react-dom           | ^16.13.1
| react-test-renderer | 16.13.1

#### Adapter

Tried either of them. Both fail installation

- [X] enzyme-adapter-react-16
- [X] enzyme-adapter-react-16.3

### Node
| library             | version
| ------------------- | -------
| Nodejs              | 15.4.0
| npm               | 7.0.15

**Comment by ljharb** [comment]
`enzyme-adapter-react-16.3` works with react 16.3. You have 16 point _thirteen_. You want `enzyme-adapter-react-16`.

Separately, you need react and react-dom to always have the same major and minor versions. You're depending on react-dom 16.4 and react 16.13, which is where the `npm` problem is coming from.

Downgrade react-dom, or upgrade react, and use `enzyme-adapter-react-16`, and everything should work.

**Comment by callmekatootie** [comment]
> enzyme-adapter-react-16.3 works with react 16.3. You have 16 point thirteen. You want enzyme-adapter-react-16.

My bad.

> Separately, you need react and react-dom to always have the same major and minor versions. You're depending on react-dom 16.4 and react 16.13, which is where the npm problem is coming from.

Thank you. I assumed that by running `npm i react-dom@16.13.1`, it would mean exact version but it does prefix the `^` to it... Removing the `^` to the `react-dom` version resolved the issue and I was able to successfully install `enzyme-adapter-react-16`.

Thank you for your quick resolution :+1:

**Comment by ljharb** [comment]
react-dom has to have a matching minor version to react.

**Comment by TommyLeong** [comment]
> react-dom has to have a matching minor version to react.

@ljharb , Thank you. I see.. I managed to install `"react-dom": "^16.13.1"`

Any thoughts about `enzyme-adapter-react-16`?
I suppose im on the right version for this?

**Comment by ljharb** [comment]
The latest version of it should work fine. If it doesn’t, please file a new issue.
