### ISSUE TITLE
Facing error - Method “simulate” is meant to be run on 1 node. 0 found instead for simulating select onchange

### ISSUE THREAD

**Issue by bhavnahari27** [enzymejs/enzyme#2490]
Facing error - Method “simulate” is meant to be run on 1 node. 0 found instead for simulating select onchange .
Below is my test case and the select of the component. Please help me and i stuck with this issue .

test case.js
```jsx
it('test handleChange() for 24h search criteria', () => {
    const wrapper = shallow(
        <Provider store={store}>
           <MyComponent />
       </Provider>
    );
    const ourEvent = {
      target: {
        value: '24h'
      }
    };
    const searchCriteriaVal = wrapper.find('select').find('option').at(1).simulate('change', {
      target: {
        value: '24h'
      }
    });
    expect(searchCriteriaVal).toEqual(ourEvent.target.value);
  });
```

**Comment by bhavnahari27** [comment]
component.js

<select id="searchCriteria" onChange={this.handleChange}>
<option value="1h">1hr</option>
<option value="24h">24hr</option>
</select>

**Comment by ljharb** [comment]
Please don’t delete the issue template - it’s there for a reason.

this is because shallow rendering doesn’t dig into MyComponent. Use the wrappingComponent option instead of directly wrapping it with Provider, and then look at `wrapper.debug()` if you’re still having trouble. `dive()` is your friend.

**Comment by bhavnahari27** [comment]
Thanks ljharb.Please help with sample code on how to implement in my case.

**Comment by ljharb** [comment]
Please first read the docs - about the wrappingComponent option and about dive.

**Comment by bhavnahari27** [comment]
I am using redux in my react project. Also i see that the basic MatchSnapShot function is not working for me . even though the snapshot file is created and testcase is passing,i dont see the html contents in that. 
Below is my component code.

It( 'matches snapshot', () => {
expect(
shallow(
<Provider store={store}>
           <MyComponent />
       </Provider>
    )
).toMatchSnapshot();
});

Please help , is there something i missing?

**Comment by ljharb** [comment]
@bhavnahari27 please fill out the issue template in #2491 and I’ll be happy to reopen it.
