### ISSUE TITLE
Matchsnapshot not working in react using redux connect function. 

### ISSUE THREAD

**Issue by bhavnahari27** [enzymejs/enzyme#2491]
I am using redux in my react project. Also i see that the basic MatchSnapShot function is not working for me . even though the snapshot file is created and testcase is passing,i dont see the html contents in that.
Below is my component code.
```jsx
It( 'matches snapshot', () => {
expect(
shallow(



)
).toMatchSnapshot();
});
```
Please help , is there something i missing?

**Comment by ljharb** [comment]
enzyme does not support or recommend snapshot testing - the closest we offer is `wrapper.debug()`.

Additionally, please always fill out issue templates in their entirety; that’s what they’re for.
