### ISSUE TITLE
Latest npm release of Enzyme (3.11.0) is using outdated object.assign

### ISSUE THREAD

**Issue by katelynsills** [enzymejs/enzyme#2501]
### Current behavior

The latest [npm release of Enzyme (3.11.0)](https://github.com/enzymejs/enzyme/blob/88dae28d8bda4c1e8582d63f9162fb1200d10ec4/packages/enzyme/package.json#L57) is using `object.assign` v4.1.0, which [has a bug that was fixed in 4.1.1](https://github.com/ljharb/object.assign/issues/82#issuecomment-776417775). The `master` branch has been [updated to v4.1.2](https://github.com/enzymejs/enzyme/blob/57baba5ceaccec7a3ada40d7559f5bf71289cbe7/packages/enzyme/package.json#L57), but no new npm release has been made. Would it be possible to release a new version of enzyme from master with the updated dependencies?

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.11.0

**Comment by ljharb** [comment]
It's using `^4.1.0`, which is a semver range - thus, it's only an end-user lockfile that would be artificially keeping it at an old version. You can rerun `npm install --save-dev enzyme` and your lockfile will be updated with the newer one.

**Comment by katelynsills** [comment]
That's a good point. That is an extra step for anyone who wishes to use it under environments that prevent mutation though, so it sounds like a release would still be preferable, but I understand the effort involved.

**Comment by ljharb** [comment]
In smaller packages, cutting a release for solely updating deps isn't that big a deal, so i'd usually do it on request, but enzyme is a bit more involved, and the main package isn't ready to be published until a number of other bugs are fixed, so I'm going to close this.

Note that any new users of enzyme, or upgraders to the latest version, will get the latest `object.assign`; it's only folks that were already on latest enzyme before the `object.assign` bugfix that will run into the need for an extra step.
