### ISSUE TITLE
simulate('mouseleave') triggers onMouseLeave event when button is disabled

### ISSUE THREAD

**Issue by tulsidaskhatri** [enzymejs/enzyme#2502]
Events like `onClick`, `onMouseEnter` and `onMouseLeave` are not triggered if button is disabled, simulate function works fine for click and mouseenter but it doesn't not work for mouseleave event.

### Current behavior
Unlike click and mouseenter, simulate triggers mouseleave for disable button.

```javascript
import {mount} from 'enzyme';

describe('button', () => {
    it('should not trigger onClick when button is disabled', () => {
        const handleClick = jest.fn();
        const wrapper = mount(
            <button disabled onClick={handleClick}>
                Text
            </button>
        );
        wrapper.simulate('click');
        expect(handleClick).not.toHaveBeenCalled();
    });
    it('should not trigger onMouseEnter when button is disabled', () => {
        const handleMouseEnter = jest.fn();
        const wrapper = mount(
            <button disabled onMouseEnter={handleMouseEnter}>
                Text
            </button>
        );
        wrapper.simulate('mouseenter');
        expect(handleMouseEnter).not.toHaveBeenCalled();
    });
    it('should not trigger onMouseLeave when button is disabled', () => {
        const handleMouseLeave = jest.fn();
        const wrapper = mount(
            <button disabled onMouseLeave={handleMouseLeave}>
                Text
            </button>
        );
        wrapper.simulate('mouseleave');
        expect(handleMouseLeave).not.toHaveBeenCalled();
    });
});
```
Third test case (`should not trigger onMouseLeave when button is disabled`) fails.

<img width="523" alt="Screenshot 2021-02-17 at 21 17 07" src="https://user-images.githubusercontent.com/2574511/108233419-94fa4f80-7165-11eb-9f6e-2d3cca0e7788.png">

### Expected behavior
Third test case (`should not trigger onMouseLeave when button is disabled`) passes.

### Your environment
MacOS
Yarn
Visual Studio Code

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.11.0
| react               | 16.14.0
| react-dom           | 16.14.0
| react-test-renderer | n/a
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
For `mount`, this behavior is controlled by `react-dom/test-utils`, so i think you'll need to file a bug on react itself for this.

**Comment by tulsidaskhatri** [comment]
reported to react
https://github.com/facebook/react/issues/20966
