### ISSUE TITLE
Support for React 17 with typescript

### ISSUE THREAD

**Issue by agnelrdx** [enzymejs/enzyme#2504]
The adapter is available for v16 (enzyme enzyme-adapter-react-16). It should support the new version of React (v17).

Using enzyme-adapter-react-16 for React v17 is throwing an error when using mount.

**Comment by ljharb** [comment]
There will be a brand new adapter for React 17. Until that time, React 17 is incompatible with enzyme, and you have to stick with React 16 to use enzyme.

Duplicate of #2429. Duplicate of #2503.
