### ISSUE TITLE
Future roadmap for Enzyme

### ISSUE THREAD

**Issue by ccreeger** [enzymejs/enzyme#2512]
Hello, I was wondering if there is an official statement regarding the future of Enzyme?

I’ve been using Jest/Enzyme since 2017 and have been very happy with it. However, my current project has us writing new tests everyday and I am wondering if we need to halt our work with Enzyme.

@ljharb and others have done a fantastic job of maintaining Enzyme since AirBnB transferred ownership. Likewise, @wojtekmaj has done great work on the React 17 adapter. Still, I have a nagging feeling that 2021 is the year that it all stops.

**Comment by wojtekmaj** [comment]
Just a note, I haven't done a lot of work with React 17 adapter, I just published WIP Pull Request, with some extra steps.  By no means I deserve the credit.

**Comment by wojtekmaj** [comment]
I think the best way to support amazing work here is to sponsor the project. I have dozens of open source projects _millions_ depend on and yet sometimes I must ignore the issues in them because I have mouths to feed.

**Comment by ljharb** [comment]
I’m not sure why your nagging feeling justifies a ridiculous claim like “the year it all stops”.

I continue to work on enzyme with whatever time i have. Sponsoring certainly helps; please do that if your company or income depends in any way on this project.

Enzyme remains the only option for testing react in a non-browser environment, and in no way will it “stop”.

The roadmap is what it always was: support every possible feature in every version of react. I have many ideas beyond that, but it’s not useful to document those until i can at least keep up with react development itself.
