### ISSUE TITLE
Enzyme intended to be pinned to "cheerio 1.0.0-rc-3" but latest version installed

### ISSUE THREAD

**Issue by alasdairhurst** [enzymejs/enzyme#2517]
### Current behavior

https://github.com/enzymejs/enzyme/blob/master/packages/enzyme/package.json#L42
As seen in the link above, enzyme is supposed to depend on `cheerio` 1.0.0-rc3. Not that it's an issue, but it's obviously intentionally pinned to that specific version. (wouldn't want to pick up any prerelease breaking changes). Unfortunately it looks like the latest is being picked up regardless. Just hit an issue after cheerio published 1.0.0-rc7
```
Module not found: Error: Can't resolve 'cheerio/lib/utils' in '/builds/amplify/api-builder/node_modules/enzyme/build'
```
They have very quickly fixed this issue, but it made it clear that something unintentional is happening in enzme for it to get installed as a dependency ;)

### Expected behavior

cheerio 1.0.0-rc3 gets installed as a dependency of enzme (or a later version, but pinned)

### Your environment

Not really applicable but will provide some details

#### Node/NPM
Node: 12.18.3
NPM: 6.14.12

#### API

- [ ] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.11.0
| react               |  15 (n/a)
| react-dom           | n/a
| react-test-renderer | n/a
| adapter (below)     | 1.4.3

#### Adapter

- [ ] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [x] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by alasdairhurst** [comment]
Wasn't expecting there to be an issue for an older version of cheerio, looks like there hasn't been a release yet.

**Comment by ljharb** [comment]
Indeed. Duplicate of #2516.

Temporary workaround is to pin cheerio in your own devDeps.
