### ISSUE TITLE
thrown: Promise {} error in static component

### ISSUE THREAD

**Issue by radionov018** [enzymejs/enzyme#2520]
![image](https://user-images.githubusercontent.com/42506537/119784772-37e60680-bed7-11eb-999c-60f777f4ceff.png)

Hello everyone!
Can anyone come across such a problem?
The component is static and don't have asynchronous logic.

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.11.0
| react               | 17.0.2
| react-dom           | 17.0.2
| adapter (below)     | 0.6.0

#### Adapter

- [x] others (enzyme-adapter-react-17)

**Comment by ljharb** [comment]
enzyme does not have a react 17 adapter yet, nor support react 17 yet - see #2429.
