### ISSUE TITLE
Function test within a promise does not recognize toHaveBeenCalledTimes

### ISSUE THREAD

**Issue by juliGer** [enzymejs/enzyme#2555]
Hello! I have a problem with the development of a test and I am not able to solve it.

I am trying to test a login which I was able to mock the fetch function and another function that I need but this last one is not recognizing the call when I try to do 

expect(functionGet).toHaveBeenCalledTimes(1)

But this is weird because if I add a console.log in the code I see the response of the mock function below I leave the code with which it fails 

## Test Fail

![Screenshot_20220402_144952](https://user-images.githubusercontent.com/49050724/161395272-c15a570b-3f26-47a3-80d5-c86073318e70.png)

## Component
![Screenshot_20220402_144856](https://user-images.githubusercontent.com/49050724/161395288-775d2cf3-7fcc-45cb-b88e-0f7a0c091c48.png)

## Result
![Screenshot_20220402_145016](https://user-images.githubusercontent.com/49050724/161395308-f61fbf31-c15a-4815-a211-d06d75c0e59e.png)

### But if I change the line of this.client.get() outside of the then it does recognize the call in the test.

![Screenshot_20220402_145131](https://user-images.githubusercontent.com/49050724/161395369-445361ec-4e9c-45ee-b380-a8db4eba958f.png)

## Result
![Screenshot_20220402_145151](https://user-images.githubusercontent.com/49050724/161395378-0df11318-ddec-41cb-b8ec-2606d1bd855a.png)

Does anyone know how to make this work? Thanks and greetings!

**Comment by ljharb** [comment]
Yes, this is a normal misunderstanding of how asynchrony works in JS.

In order for your test to make an assertion about client.get, the test has to "know" what to wait for. In other words, unless the test can access the promise created by the `.then` - that resolves after the .get is called - it's simply *not possible* to test this.

This isn't unique to enzyme, react, jest, or fetch, it's just how async works in JS.

**Comment by juliGer** [comment]
> Yes, this is a normal misunderstanding of how asynchrony works in JS.
> 
> In order for your test to make an assertion about client.get, the test has to "know" what to wait for. In other words, unless the test can access the promise created by the `.then` - that resolves after the .get is called - it's simply _not possible_ to test this.
> 
> This isn't unique to enzyme, react, jest, or fetch, it's just how async works in JS.

Ah I understand thank you very much!
