### ISSUE TITLE
Component is not re-rendered with updated states

### ISSUE THREAD

**Issue by juliGer** [enzymejs/enzyme#2557]
Hello! I wanted to see if someone can give me a hand regarding a question I have that I do not know if it is possible to do, and if it is I would like to know what I'm doing wrong so that it does not work.

I have a component that reads a state and that shows it on the screen

- Before setstate
  Chats Operator(0) 

- After setstate
  Chats Operator(4) 

I see the updated states if I print .instance().state but I would need to render it again with the updated state, I tried .update() as shown in the image but I would not be getting the result I want 

Is it possible to do this with enzyme ? Thanks and greetings!

## Component
![Screenshot_20220407_121516](https://user-images.githubusercontent.com/49050724/162234958-f4c71add-bc02-4986-9ec8-e8363ec397d2.png)

## Test
![Screenshot_20220407_121727](https://user-images.githubusercontent.com/49050724/162235077-966ad428-44ca-438d-a5cd-fdb003822ac0.png)

## Result Test (Bad)
![Screenshot_20220407_121655](https://user-images.githubusercontent.com/49050724/162235270-e9cbcd77-3728-4424-95d4-05a9f62bf3c7.png)

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |3.11.0
| react               |16.8.6 
| react-dom           | 16.8.6
| react-test-renderer | 
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Could you make a codesandbox, with relevant component and test code, that reproduces the error?

**Comment by juliGer** [comment]
> Could you make a codesandbox, with relevant component and test code, that reproduces the error?

There I tried a smaller code in codesandbox and it worked so it must be something of mine, I am going to review the issue is that I cannot put the code because it is private but I consider the issue closed
Thank you very much for answering, greetings!

**Comment by juliGer** [comment]
Hello! I have been able to replicate the error, the problem is that when I want to use mount() with a library called notistack I get this error 

## Test bad
  https://codesandbox.io/s/shallow-test-app-forked-s7bj8o?file=/src/App.test.js

![image](https://user-images.githubusercontent.com/49050724/162440365-13f58301-0230-43d7-a2ec-5e723927a043.png)

If you run the tests you can see how it only prints once cant with value 0 and the expected behavior is that it prints 

cant: 0
cant: 1

That is, if I don't use notistack, the code performs the expected behavior. Hopefully there is a solution. Thanks and greetings again!

![image](https://user-images.githubusercontent.com/49050724/162440137-2e504e8c-c40d-44bf-8430-30e35b6b6540.png)

**Comment by ljharb** [comment]
The provider should be passed in with the `wrappingComponent` option, not directly wrapping the jsx of the thing you want to test.

**Comment by juliGer** [comment]
> The provider should be passed in with the `wrappingComponent` option, not directly wrapping the jsx of the thing you want to test.


Oh it went thank you very much!! You're a genius!!
