### ISSUE TITLE
Cheerio 1.0.0-rc.11 no longer support deep imports

### ISSUE THREAD

**Issue by ryanrd** [enzymejs/enzyme#2558]
### Current behavior

    Cannot find module 'cheerio/lib/utils' from 'node_modules/enzyme/build/Utils.js'

packages/enzyme/src/Utils.js

`import { isHtml } from 'cheerio/lib/utils';`

### Expected behavior

no error

#### Version

| library             | version
| ------------------- | -------
| enzyme              | latest

#### Adapter

N/A

**Comment by ljharb** [comment]
You're right; the next release of enzyme pegs cheerio to [1.0.0-rc.3](https://github.com/enzymejs/enzyme/blob/master/packages/enzyme/package.json#L42) - you can peg this yourself in the meantime in your package.json.

**Comment by vbhayden** [comment]
Why not just add the little `isHtml` function into the enzyme file that's trying to import it?  It's all of 8 lines and would save the dependency pegging.

**Comment by ljharb** [comment]
@vbhayden that is certainly another alternative.
