### ISSUE TITLE
Hi @ljharb / @lelandrichardson @koba04 @nfcampos ,

### ISSUE THREAD

**Issue by Mmggcjitfjo** [enzymejs/enzyme#2567]
Hi @ljharb / @lelandrichardson @koba04 @nfcampos ,
Can someone take a look at this PR and approve. This will fix security vulnerability with nth-check@1.2.0 which is downloaded transitively using enzyme.

_Originally posted by @vinodkumarsharma276 in https://github.com/enzymejs/enzyme/issues/2561#issuecomment-1154165892_

**Comment by ljharb** [comment]
Please don't file spam issues from other people's comments.
