### ISSUE TITLE
How to test the form which is rendered based on props in class component in react.js ?

### ISSUE THREAD

**Issue by yogendrakumar96** [enzymejs/enzyme#2568]
Here I want to test the form if create ticket is there then I should render the form otherwise I want to render the error. How to test it any idea about this ?

```
{ 
createTicket != undefined ? <div className="container">
<form onSubmit={this.onSubmit} id="ticket-form"><DynamicFormField /></form></div> : <ErrorUI/>
}
```

**Comment by ljharb** [comment]
I'm not sure what you're asking.

If you have a prop (`createTicket`) whose value influences which components are rendered, you'd do multiple shallow tests, one for each variation of `createTicket`, and assert on what things are rendered in each case.

**Comment by yogendrakumar96** [comment]
> I'm not sure what you're asking.
> 
> If you have a prop (`createTicket`) whose value influences which components are rendered, you'd do multiple shallow tests, one for each variation of `createTicket`, and assert on what things are rendered in each case.

> I want to test this form rendering based create ticket props. If the create ticket props is there then I want to render the component. How to do this ? can you please tell me ?

**Comment by ljharb** [comment]
It sounds like you’re just asking how to write tests in general - I’d suggest StackOverflow, IRC, or Slack for that, as i can’t offer that service here.
