### ISSUE TITLE
Document `getElement(s)` for full DOM rendering

### ISSUE THREAD

**Issue by andrewiggins** [enzymejs/enzyme#2574]
Hello!

When browsing the Enzyme docs, I noticed that `getElement(s)` is not documented as a method under "Full DOM Rendering" but does appear to be [supported by the ReactWrapper](https://github.com/enzymejs/enzyme/blob/9bb92eb6dad19152766549bb22039264982e673b/packages/enzyme-test-suite/test/ReactWrapper-spec.jsx#L1066).

**Describe the solution you'd like**
Document the behavior of `getElement(s)` for full DOM rendering.

**Comment by ljharb** [comment]
Hm, you're right, https://enzymejs.github.io/enzyme/docs/api/ShallowWrapper/getElements.html and https://enzymejs.github.io/enzyme/docs/api/ShallowWrapper/getElement.html exist but not the ReactWrapper variants.

I'll add these.

**Comment by ljharb** [comment]
They'll be published the next release of `enzyme`.

**Comment by andrewiggins** [comment]
Sounds good! Thank you
