### ISSUE TITLE
Need help in my game need for speed no limit


### ISSUE THREAD

**Issue by Mmggcjitfjo** [enzymejs/enzyme#2578]
SHARING BY SHAREIT  ![Nexters_OurStory.pdf](https://github.com/enzymejs/enzyme/files/10715154/Nexters_OurStory.pdf)

**Comment by Mmggcjitfjo** [comment]
I need help in need for speed no limit on my android phone

**Comment by ljharb** [comment]
@Mmggcjitfjo you won't find help for a video game on a random github repo.
