### ISSUE TITLE
Is this library 'dead'?

### ISSUE THREAD

**Issue by nicolasOtalora** [enzymejs/enzyme#2596]
Hi,
Just wanted to know whether this library is already 'dead' or at least technical support is still provided. The project I work for has been evaluating if it would be convenient to remain using Enzyme (mainly due to its shallow render feature). 
Regards!

**Comment by ljharb** [comment]
Nope, it's not. Support is still provided, and development continues.

I still plan on supporting react 17 and 18 (etc), but sufficient time and money has not yet been made available for me to get the work done.

**Comment by ljharb** [comment]
@yairEO development != releases, and there have been new releases of the adapters.

**Comment by yairEO** [comment]
Well, I cannot use code which is not released through `npm publish` (and I have no use for the adapters).

May I know the reason *Enzyme* itself has not released any update in years? The pile of open issues and the lack of released raises this question...

**Comment by ljharb** [comment]
I’m confused, everyone needs an adapter to use enzyme.

The reason is that i don’t cut releases until I’m prepared to triage bug reports that come in, and enzyme requires more time than most.
