### ISSUE TITLE
 update nearley package from 2.7.10 to 2.20.1 

### ISSUE THREAD

**Issue by kalairaj1403** [enzymejs/enzyme#2605]
enzyme@^3.11.0: 
dependency
rst-selector-parser "^2.2.3" 

rst-selector-parser "^2.2.3" 
dependency
 lodash.flattendeep "^4.4.0" 
nearley "^2.7.10"

is possible to update sub dependencies nearley from 2.7.10 to 2.20.1 in rst-selector-parser "^2.2.3" in my project
or please suggest how to resolve this issue

nearley@^2.7.10: dependency "nomnom": "~1.6.2", "railroad-diagrams": "^1.0.0", "randexp": "^0.4.2"
nomnom package is deprecated

nearley@^2.20.1 does not have nomnom package

nearley@^2.20.1: dependency commander "^2.19.0" moo "^0.5.0" railroad-diagrams "^1.0.0" randexp "0.4.6"

**Comment by ljharb** [comment]
This needs to be done in your own lockfile; enzyme has nothing to do with it and can’t have anything to do with it.
