### ISSUE TITLE
Proposal: Add a `mount` function that acts as a context manager for a component

### ISSUE THREAD

**Issue by griffinmyers** [enzymejs/enzyme#437]
Neither enzyme's `mount` nor TestUtil's `renderIntoDocument` will clean up a component when you're done testing it (i.e., unmount it and ensure proper life-cycle methods are invoked.)  This can be problematic when your component has side-effects like listening to a global store singleton for updates, in which case each component you ever mount in your test suite will forever listen to store broadcasts, which could prohibitively clog your runtime's event loop. 

While coupling global state into a component's unit test is surely an anti-pattern, I'm confident this subtle issue is lurking it many react test suites.

I think enzyme is in a great position to a) raise awareness so developers are at least conscious of their components never being unmounted and b) provide a clean interface for safely mounting a component and ensuring it is automatically cleaned up when any assertions have completed.  I have a demo of this problem and a proposed solution here: https://github.com/griffinmyers/react-test, but the tl;dr of it is something like this: 

``` javascript
it('safeMounts', function() {
  safeMount(<Baz />, function(wrapper) {
    expect(wrapper.find('.baz').length).to.equal(1);
  });
});

it('safeMounts async', function(done) {
  safeMount(<Baz />, function(wrapper, unmount) {
    expect(wrapper.state('mountedOneSecondAgo')).to.equal(false);
    setTimeout(() => {
      expect(wrapper.state('mountedOneSecondAgo')).to.equal(true);
      unmount();
    }, 1000);
  }, done);
});
```

I'd love to hear some thoughts from you folks and am happy to work up a PR if you think this is something worth pursuing.

**Comment by Aweary** [comment]
Hey @griffinmyers, thanks for the idea.

> Neither enzyme's mount nor TestUtil's renderIntoDocument will clean up a component when you're done testing it (i.e., unmount it and ensure proper life-cycle methods are invoked.) 

If you call `unmount` on a wrapper returned from `mount` it should call `componentWillUnmount` 

```js
const wrapper = mount(<Component/>);
// do your tests
wrapper.unmount();
// validate its unmounted
```

If that's not working, definitely let me know because it should and I think that it's the API we should stick with. It may be interesting to somehow automatically call `unmount` when a wrapper is no longer finished, but that's complex and I think ultimately it should be up to the tester to explicitly mount and unmount.

>While coupling global state into a component's unit test is surely an anti-pattern, I'm confident this subtle issue is lurking it many react test suites.

I would agree that its an anti-pattern, which means I wouldn't want to make it any easier for anyone. Global stores are usually mocked and reset in `beforeEach` which avoids this completely.

>I think enzyme is in a great position to a) raise awareness so developers are at least conscious of their components never being unmounted and b) provide a clean interface for safely mounting a component and ensuring it is automatically cleaned up when any assertions have completed.

I agree here too, but I'd rather we should just:

1) document that you should call `unmount` if your component if you need to validate that the `componentWillUnmount` method is cleaning up subscriptions as it should

2) document that global state should be reset between tests whenever possible to avoid data leaks like this.

**Comment by griffinmyers** [comment]
Thanks for the thoughts @Aweary.  Yeah, you may be right that this is just a matter of documentation.  A few spots that jump out to me would be to explicitly call `unmount` in all examples of [full-dom rendering](http://airbnb.io/enzyme/docs/api/mount.html) and maybe disambiguate on the [detach() page](http://airbnb.io/enzyme/docs/api/ReactWrapper/detach.html), which lead me to believe that if I didn't specify `attachTo` enzyme would clean up *for* me (any maybe it's the term *clean up* that's somewhat overloaded). 

>  It may be interesting to somehow automatically call unmount when a wrapper is no longer finished, but that's complex and I think ultimately it should be up to the tester to explicitly mount and unmount.

That's what this context manager does.  Unfortunately we don't have anything like RAII in javascript and thus no hooks into destructing (not that they would fire anyways because our stores would still hold references to all our components).  I think this is a safer default, probably what most people intend to do when they `mount()` a component, and also convenient.  But, I appreciate that interfaces are sacred!  Happy to alternatively brainstorm ways we can make the docs better.

**Comment by Aweary** [comment]
I'm not totally against having something like what you're recommending here, a function like `mount` that invokes `unmount` after invocation. I'll have to think about it more. We don't really have any other API that does that, so I just want to be sure we remain consistent when possible.

**Comment by griffinmyers** [comment]
Closing this issue, it's stale to me as the submitter and I assume the folks maintaining enzyme. Of course, feel free to re-open if it's of active interest to anyone.
